Rev-007-create-login-page
abukhadraop-or/reverifi pull request #10
Opened 2021-12-22 11:11 UTC by IbrahimAldereni-socuimtech

![LOGIN-PAGE](https://user-images.githubusercontent.com/92721815/147083562-67650e09-ffb8-4353-bdff-89ee0a7ce8c2.png)

- figma link:
https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A15050

-REV-006 signup page PR (base)
https://github.com/abukhadraop-or/reverifi/pull/9

2021-12-27 13:54 UTC, NoorAbuzainahOP commented on src/pages/Login/login.styles.js
> +`;
I noticed that some of the styled components here are duplicate with the ones in `src/pages/SignUp/sign-up.styles.js`, so let's reuse the same components if possible.
I'd suggest moving some components to the shared components directory and make accessible, e.g. we can move this to `src/components/Image`. Same thing goes for the rest of the components

2021-12-27 14:12 UTC, NoorAbuzainahOP commented
This probably came up from a previous PR, but some files naming seem kind of redundant e.g. `src/pages/Login/Login.jsx`
would make more sense to use naming convention similar to the below?
```
├── Login
│   ├── index.jsx
│   ├── schema.js
│   ├── style.js
│   └── test.jsx
```

2021-12-27 14:27 UTC, IbrahimAldereni-socuimtech commented on src/pages/Login/login.styles.js
> +`;
some styling differs from the signup, that why I separated them

2021-12-27 15:12 UTC, NoorAbuzainahOP commented on src/pages/Login/Login.jsx
> +          <ErrorMessage>{errors.email?.message}</ErrorMessage>
I noticed that every InputField component needs an ErrorMessage, let's create a shred jsx component for both.

2021-12-27 15:19 UTC, NoorAbuzainahOP commented on src/pages/Login/Login.jsx
> +          </CheckboxInputContainer>
same here

2021-12-27 15:20 UTC, NoorAbuzainahOP commented on src/pages/Login/Login.jsx
> +          </SocialButton>
we can use a list of buttons here as well

2021-12-28 09:28 UTC, abukhadraop requested changes

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/Login/Login.jsx
> +  const onSubmit = () => {
All functions should have docs

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/Login/Login.test.jsx
> +describe('test2', () => {
lets remove anything related to unit tests for now

2021-12-28 09:28 UTC, abukhadraop commented on package-lock.json
>        "dependencies": {
please revert all changes on this file

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/Login/LoginSchema.js
> +import * as yup from 'yup';
we use kebab case for `.js` files

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/Login/LoginSchema.js
> +    password: yup
please add label to these fields as we did in the sign up schema

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/SignUp/SignUp.test.jsx
> +describe('test', () => {
please remove this file

2021-12-28 09:28 UTC, abukhadraop commented on src/setupTests.js
>  import Enzyme from 'enzyme';
please remove this file

2021-12-28 09:28 UTC, abukhadraop commented on src/styles/colors.js
> +  darkshadow: '#22222229',
color opacity does not change the color itself, this file should only contain unique colors to make them reusable, you can append the opacity to the color when you use it, ex:
https://github.com/abukhadraop-or/reverifi/blob/d92893233670c6ecbe5dff52e208d086c02c65ba/src/components/FeaturedListing/Card/card.styles.js#L86

2021-12-28 09:28 UTC, abukhadraop commented on src/styles/colors.js
> +  lightblue: '#0084fc',
i dont see these colors used anywhere, why they added?

2021-12-28 09:28 UTC, abukhadraop commented on src/styles/colors.js
> +  midgrey: '#d8d8d8',
we use camelcase naming for object properties, why this renamed to `midgrey` ?

2021-12-28 09:28 UTC, abukhadraop commented on src/routes.js
> +    path: '/signUp',
please revert this changes

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/SignUp/sign-up.styles.js
> -
any reason why these empty lines were removed ? i added them to make the styles more readable

2021-12-28 09:28 UTC, abukhadraop commented on src/pages/SignUp/sign-up.styles.js
>    ${mq.desktopWide`
lets use the mobile breaking point here and in the login page

2021-12-28 10:58 UTC, abukhadraop approved these changes

2021-12-28 10:59 UTC, merged