REV-109 search listings cards
abukhadraop-or/reverifi pull request #110
Opened 2022-02-08 16:36 UTC by IbrahimAljabrST

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-109

### Description
-user can see search box at the top of the page
-user is able to insert a city name into search box
-user is able to insert a ZIP code into search box
-User is able to cancel the search by clicking on x button in the search box
-User is able to submit the search by pressing “enter”
-User is able to submit the search by clicking on search icon
-User is able to see number of results after proceed with the search

2022-02-08 18:39 UTC, AhmadAlShwaiki commented on src/components/home/Storyboard/index.jsx
> +        `${appPaths.listingPaths.search}?key=${inputValue.current.value}`
destruct please
```suggestion
        `${listingPaths.search}?key=${inputValue.current.value}`
```

2022-02-08 18:41 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/index.jsx
> +              if (e.key === 'Enter') {
Please use [keyCodes](https://css-tricks.com/snippets/javascript/javascript-keycodes/)

2022-02-08 18:42 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/listing-search-cards.style.js
> +export const SorryMessage = styled.div`
```suggestion
export const Container = styled.div`
```
To hold both messages

2022-02-08 18:43 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/listing-search-cards.style.js
> +  svg {
Please create a styled component

2022-02-08 18:44 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/listing-search-cards.style.js
> +  color: ${colors.dustyGray};
```suggestion
export const Text = styled.p`
....
```
Please create one shared Text then extend your components

2022-02-09 09:14 UTC, mohdabed123 requested changes

2022-02-09 09:14 UTC, mohdabed123 commented on src/components/listing-search-page/Card/card.style.js
>  export const Badge = styled.div`
why are we using a div instead of heading

2022-02-09 10:32 UTC, IbrahimAljabrST commented on src/components/listing-search-page/SearchResults/index.jsx
> +      {cardData?.length ? (
empty array will give true

2022-02-09 19:58 UTC, AhmadAlShwaiki commented on src/components/home/Storyboard/index.jsx
> +    inputValue.current.value = '';
```suggestion
    setCheckValue```

2022-02-09 19:59 UTC, AhmadAlShwaiki commented on src/components/home/Storyboard/index.jsx
> +  const [checkValue, setCheckValue] = useState(null);
```suggestion
  const [address, setAddress] = useState(null);
```

2022-02-09 20:04 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/Card/index.jsx
> +          ) : null}
Same for all other elements please 
```suggestion
          {bedrooms && (
            <IconsNumber>
              {data.bedrooms}
              <Bed />
            </IconsNumber>
          ) }
```

2022-02-09 20:05 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/index.jsx
>    const [keyWord, setKeyWord] = useState(window.location.href.split('=')[1]);
```suggestion
useLocation()
```

2022-02-09 20:08 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/index.jsx
> +  const [resultCount, setResultCount] = useState(0);
```suggestion
```

2022-02-09 20:12 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/index.jsx
> +          </ResultCount>
This component change in satet
```suggestion
          <ResultCountContainer>
            <ResultNumber>{results.?length ? results.?length: 0 }</ResultNumber>
            <ResultText>{keyWord}</ResultText>
          </ResultCountContainer>
```
Can you please explain to me why are you using state for component management here?

2022-02-09 20:13 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/index.jsx
> +          {/* todo */}
```suggestion
Please remove this, you can manage all actions and items to add in Jira tickets
```

2022-02-10 16:46 UTC, AhmadAlShwaiki approved these changes

2022-02-13 14:40 UTC, mohdabed123 approved these changes

2022-02-14 15:13 UTC, merged