REV-113 enter key not working in log in and sign up page
abukhadraop-or/reverifi pull request #115
Opened 2022-02-10 09:05 UTC by IbrahimAljabrST

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-113

### Description

fixed enter key not working for login and sign up pages

2022-02-10 10:16 UTC, AhmadAlShwaiki commented on src/components/shared/FormInput/index.jsx
> +  onClickInputKey: PropTypes.func,
I can see these values as required, they're always occurring, can you please update this component accordingly?
               ```
                  name=""
                  error={errors.field?.message}
                  label=""
                  register={}
                  type={}
                  onChange={() => doSomething('')}
```

2022-02-10 10:18 UTC, AhmadAlShwaiki commented on src/pages/Login/Login.jsx
> +  const continueButton = useRef(null);
👍

2022-02-10 10:19 UTC, AhmadAlShwaiki requested changes
Looks good, just minor changes in the FormInput component

2022-02-13 13:36 UTC, mohdabed123 approved these changes

2022-02-14 08:16 UTC, AhmadAlShwaiki approved these changes

2022-02-14 15:52 UTC, merged