Transaction first step
abukhadraop-or/reverifi pull request #139
Opened 2022-02-17 15:25 UTC by Fkayyali

### Jira URL

https://optimumpartners.atlassian.net/browse/JIRA_ISSUE_ID

### Description

_What problem is this branch meant to solve, what changes does it make, and how do these changes fix that problem?_

### Dependencies in Other PRs,Repo

_If this pull request relates to or depends on any changes in backend/frontend repo PR link it here._

### Testing Instructions

_How to test this and check for any possible regressions. Provide test data when applicable._

2022-02-20 09:20 UTC, AhmadAlShwaiki commented on package-lock.json
> +        "react-select": "^5.2.2",
Please remove this file from this commit

2022-02-20 09:22 UTC, AhmadAlShwaiki commented on src/assets/gray-mail.svg
> +<svg width="13" height="10" viewBox="0 0 13 10" fill="none" xmlns="http://www.w3.org/2000/svg">
I remember seeing some of these values already, like the agent picture, please make sure to remove any repeated assets.

2022-02-20 09:23 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/add-involved-parties.styles.js
> +  color: #222222;
```suggestion
  color: colors.myColor;
```

2022-02-20 09:23 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/add-involved-parties.styles.js
> +  font-size: 24px;
```suggestion
  font-size: my-value rem;
```

2022-02-20 09:24 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/index.jsx
> +  // const [selectedAgent, setSelectedAgent] = useState();
```suggestion
```

2022-02-20 09:25 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/index.jsx
> +  ];
```suggestion
 Can just render names and then change the first letter toUpperCase
```

2022-02-20 09:26 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/index.jsx
> +  // const agentOptions2 = ['faris', 'ammar', 'tamam', 'yousef', 'sara'];
```suggestion
```

2022-02-20 09:26 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/index.jsx
> +    console.log(data);
```suggestion
```

2022-02-20 09:26 UTC, AhmadAlShwaiki commented on src/components/transaction/AddInvolvedParties/index.jsx
> +    //  getValues,
```suggestion
```

2022-02-27 13:14 UTC, AhmadAlShwaiki approved these changes

2022-02-27 13:44 UTC, mohdabed123 approved these changes

2022-03-02 15:04 UTC, IbrahimAldereni-socuimtech requested changes

2022-03-08 14:34 UTC, IbrahimAldereni-socuimtech approved these changes

2022-03-08 14:35 UTC, merged