REV-150-agent-profile-rate-and-review
abukhadraop-or/reverifi pull request #160
Opened 2022-02-23 16:34 UTC by IbrahimAldereni-socuimtech

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-150

### Description

- create add, update, get user reviews
- figma link: https://www.figma.com/file/IKofGteYvhvMoXoafbBpgi/reverifi?node-id=1692%3A6631

### Dependencies in Other PRs,Repo

- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/36

![Screenshot from 2022-02-23 17-20-56](https://user-images.githubusercontent.com/92721815/155363690-655afc1d-3963-45ce-9b72-1b0b9b553b87.png)
![Screenshot from 2022-02-23 17-21-04](https://user-images.githubusercontent.com/92721815/155363708-16fc3e9a-c5fd-42dc-8bb4-3c99b613ef0c.png)

2022-02-23 16:58 UTC, AhmadAlShwaiki commented on src/components/agent-details/AgentRating/agent-rating-schema.js
> +      .required('Please fill out this field')
```suggestion
      .required('This field can not be empty')
```

2022-02-23 16:59 UTC, IbrahimAldereni-socuimtech commented on src/components/agent-details/AgentRating/agent-rating-schema.js
> +      .required('Please fill out this field')
that's what Duah wants

2022-02-23 17:00 UTC, IbrahimAldereni-socuimtech commented on src/components/agent-details/AgentRating/agent-rating.style.js
> +  textarea {
I am using shared component

2022-02-23 17:05 UTC, mohdabed123 requested changes

2022-02-23 17:05 UTC, mohdabed123 commented on src/components/shared/LikeButton/index.jsx
> +function LikeButton({ grayIcon, active }) {
```suggestion
function LikeButton({ isLiked, active }) {
```

2022-02-23 17:05 UTC, mohdabed123 commented on src/components/shared/FormTextArea/form-text-area.styles.js
> +    isLabeled ? 'space-between' : 'flex-end'};
```suggestion
    hasLabel ? 'space-between' : 'flex-end'};
```

2022-02-23 17:07 UTC, mohdabed123 commented on src/components/agent-details/AgentRating/agent-rating-schema.js
> +      .required('Please fill out this field')
you can use either this one or the one ahmad recommended as you see fit

2022-02-23 17:08 UTC, IbrahimAldereni-socuimtech commented on src/components/agent-details/AgentRating/agent-rating-schema.js
> +      .required('Please fill out this field')
that's the recommandation of Duha

2022-02-23 17:09 UTC, IbrahimAldereni-socuimtech commented on src/components/shared/LikeButton/index.jsx
> +function LikeButton({ grayIcon, active }) {
thats for styling, sometimes we use different icons colors, not for functinality

2022-02-24 14:17 UTC, AhmadAlShwaiki approved these changes

2022-02-27 09:11 UTC, merged