REV-146 my listings page bugs
abukhadraop-or/reverifi pull request #162
Opened 2022-02-26 20:51 UTC by IbrahimAljabrST

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-146

### Description

my listings page bugs

### Dependencies in Other PRs,Repo

https://github.com/abukhadraop-or/reverifi-api/pull/38

2022-02-27 16:43 UTC, mohdabed123 requested changes

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/ListingsHeader/index.jsx
> +/* eslint-disable react/prop-types */
```suggestion
```

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/ListingsHeader/index.jsx
>   */
update docs

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/ListingsTable/index.jsx
> +/* eslint-disable no-unused-vars */
```suggestion
```

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/ListingsTable/index.jsx
>   *
update docs

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/ListingsTable/index.jsx
> +              <TableCellContainer>
```suggestion
              <CellContainer>
```

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/ListingsTable/index.jsx
> +        <ArrowIconContainer onClick={handleLeftArrowClick}>
```suggestion
        <IconContainer onClick={handleLeftArrowClick}>
```

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/MyListings/index.jsx
> +    if (pageNumber < Math.floor(listings?.count / listingPerPage)) {
```suggestion
    if (pageNumber < Math.trunc(listings?.count / listingPerPage)) {
```

2022-02-27 16:43 UTC, mohdabed123 commented on src/components/my-listings/MyListings/index.jsx
> +      {listings?.count > 0 ? (
```suggestion
      {listings? ? (
```

2022-02-28 07:22 UTC, IbrahimAljabrST commented on src/components/my-listings/MyListings/index.jsx
> +      {listings?.count > 0 ? (
this will return true without the .count

2022-03-02 08:50 UTC, mohdabed123 approved these changes

2022-03-02 08:50 UTC, merged