REV-164-create-listings-page-stats
abukhadraop-or/reverifi pull request #164
Opened 2022-02-27 10:40 UTC by IbrahimAldereni-socuimtech

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-164

### Description

- add save, view, share for listing and user

### Dependencies in Other PRs,Repo

- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/39

2022-02-27 16:55 UTC, mohdabed123 requested changes

2022-02-27 16:55 UTC, mohdabed123 commented on src/components/agent-list/AgentCard/agent-card.styles.js
> +export const FooterButtonsContainer = styled.div`
```suggestion
export const ButtonsContainer = styled.div`
```

2022-02-27 16:55 UTC, mohdabed123 commented on src/components/listing-page/Offer/index.jsx
> +function Offer({ price, address, id }) {
update docs

2022-02-27 16:55 UTC, mohdabed123 commented on src/components/listing-page/Overview/index.jsx
> +                &nbsp;
```suggestion
```

2022-02-27 16:55 UTC, mohdabed123 commented on src/components/shared/SaveAndShareButtons/index.jsx
> +function SaveAndShareButtons({ userId, listingId, setShowModal, small }) {
add docs

2022-02-27 16:55 UTC, mohdabed123 commented on src/components/shared/SaveAndShareButtons/save-and-share-buttons.styles.js
> +  height: ${({ small }) => (small ? '1.1rem' : '1.125rem')};
can't we just use the same size without this , it doesn't really make much of a difference

2022-02-27 16:55 UTC, mohdabed123 commented on src/components/shared/SaveAndShareButtons/save-and-share-buttons.styles.js
> +  padding: ${({ small }) => (small ? '0 0.23rem' : '0 0.37rem')};
same thing here , not much of a difference

2022-02-28 07:28 UTC, IbrahimAldereni-socuimtech commented on src/components/shared/SaveAndShareButtons/save-and-share-buttons.styles.js
> +  padding: ${({ small }) => (small ? '0 0.23rem' : '0 0.37rem')};
yes i need them like that cuz these are small icons and these slight differences affect the design

2022-02-28 15:09 UTC, mohdabed123 approved these changes

2022-02-28 15:09 UTC, merged