REV-153-create-listings-implement-special-tags
abukhadraop-or/reverifi pull request #165
Opened 2022-02-27 14:52 UTC by IbrahimAldereni-socuimtech

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-153

### Description

- add tags input to create listing page

### Dependencies in Other PRs,Repo

- backend PR: https://github.com/abukhadraop-or/reverifi-api/pull/40

![Screenshot from 2022-02-27 17-51-12](https://user-images.githubusercontent.com/92721815/155887270-43c1b0cf-1a30-4eb1-b120-1135ca57ed7a.png)

2022-02-27 16:58 UTC, mohdabed123 requested changes

2022-02-27 16:58 UTC, mohdabed123 commented on src/components/create-listing/CreateListingForm/index.jsx
> +    control,
update docs for date

2022-02-27 16:58 UTC, mohdabed123 commented on src/components/home/FeaturedListingCard/index.jsx
> +            {tags?.length > 0 && tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}
```suggestion
            {tags && tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}
```

2022-02-27 16:58 UTC, mohdabed123 commented on src/components/listing-search-page/Card/index.jsx
> +          {tags?.length > 0 &&
```suggestion
          {tags &&
```

2022-02-28 07:09 UTC, IbrahimAldereni-socuimtech commented on src/components/home/FeaturedListingCard/index.jsx
> +            {tags?.length > 0 && tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}
tags alone won't work cuz it's array

2022-03-01 12:18 UTC, mohdabed123 approved these changes

2022-03-01 12:18 UTC, merged