REV-018-create-phone-verification-page
abukhadraop-or/reverifi pull request #19
Opened 2021-12-23 17:02 UTC by IbrahimAldereni-socuimtech

![VERIFY-PHONE](https://user-images.githubusercontent.com/92721815/147271297-6e2e3c57-434c-4c9b-b30f-9dfb8c791307.png)

- figma link:
https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A13259

2021-12-30 17:22 UTC, AseelRousan-op commented on src/pages/VerifyPhone/CodeForm/code-form.styles.js
> +  border: 3px solid ${colors.midGrey};
```suggestion
  border:    0.1875rem solid ${colors.midGrey};
```

2021-12-30 17:22 UTC, AseelRousan-op commented on src/routes.js
> +    title: 'Verify Phone',
```suggestion
    title: 'VerifyPhone',
```

2021-12-30 17:22 UTC, AseelRousan-op commented on src/pages/VerifyPhone/CodeForm/code-form.styles.js
> +    }
Can we replace these with separate styled-components, for example
```
export const CancelButton = styled(Button)`
      background-color: ${colors.white};
      border: 1px solid ${colors.gray};
      color: ${colors.gray};
`
```
and override the hover and any other styles to match the design you want but using the shared Button component

2022-01-03 08:00 UTC, IbrahimAldereni-socuimtech commented on src/pages/VerifyPhone/CodeForm/code-form.styles.js
> +  border: 3px solid ${colors.midGrey};
border width values always in px

2022-01-03 15:43 UTC, Mahmoudzaid2994 commented on src/pages/Login/Login.jsx
>    LoginContainer,
https://github.com/abukhadraop-or/reverifi/blob/458c37f90169c526c2a48dd31896767f77e24543/src/pages/Login/Login.jsx#L16-L27

change it to this code
>  AppleButton,
  FacebookButton,
  Form,
  GoogleButton,
  ImageContainer,
  InfoContainer,
  InputWrapper,
  LinkText,
  LoginContainer,
  OrText,
  SocialLinksContainer,
  Title,

2022-01-03 15:43 UTC, Mahmoudzaid2994 commented on src/pages/Login/Login.jsx
>          <SocialLinksContainer>
https://github.com/abukhadraop-or/reverifi/blob/458c37f90169c526c2a48dd31896767f77e24543/src/pages/Login/Login.jsx#L103-L120

change it please to this code

          <SocialButton backgroundColor={colors.blue}>
            <div>
              <FacebookIcon />
              <span> Continue with Facebook</span>
            </div>
          </SocialButton>
          <SocialButton backgroundColor={colors.mineShaft}>
            <div>
              <AppleIcon />
              <span> Continue with Apple</span>
            </div>
          </SocialButton>
          <SocialButton
            backgroundColor={colors.white}
            border={`1px solid ${colors.mercury}`}
            color={colors.mineShaft}
          >
            <div>
              <GoogleIcon />
              <span>Continue with Google</span>
            </div>
          </SocialButton>

2022-01-03 15:43 UTC, Mahmoudzaid2994 commented on src/pages/VerifyPhone/CodeForm/code-form.styles.js
> +`;
Please move the hover style to the base button component and use it as default

```suggestion

```

2022-01-03 15:43 UTC, Mahmoudzaid2994 commented on src/pages/VerifyPhone/CodeForm/code-form.styles.js
> +`;
pass these styles as props at `CodeForm.jsx`

```suggestion
```

2022-01-03 15:45 UTC, Mahmoudzaid2994 commented
https://github.com/abukhadraop-or/reverifi/blob/458c37f90169c526c2a48dd31896767f77e24543/src/pages/Login/login.styles.js#L81-L92

change to this code

> export const SocialButton = styled(Button)`
  margin-top: 0.625rem;

2022-01-03 15:46 UTC, Mahmoudzaid2994 commented on src/pages/Login/login.styles.js
> +
```suggestion
export const SocialButton = styled(Button)`
  margin-top: 0.625rem;
```

2022-01-03 15:47 UTC, Mahmoudzaid2994 commented
please remove these

https://github.com/abukhadraop-or/reverifi/blob/458c37f90169c526c2a48dd31896767f77e24543/src/pages/Login/login.styles.js#L105-L117

2022-01-03 17:00 UTC, Mahmoudzaid2994 commented on src/pages/VerifyPhone/CodeForm/CodeForm.jsx
> +
Please add docs here and at all functions

2022-01-03 20:14 UTC, AhmadAlShwaiki commented on src/pages/VerifyPhone/verify-phone.styles.js
> +  padding: 0 0.625rem;
Any css property/ value that doesn't make a lot of difference in comparison to figma should be removed. This will keep your code shorter, cleaner; Thus easier to track/debug.

2022-01-03 20:15 UTC, AhmadAlShwaiki commented on src/pages/VerifyPhone/verify-phone.styles.js
> +  padding: 0 0.625rem;
Any css property/ value that doesn't make a lot of difference in comparison to figma should be removed. This will keep your code shorter, cleaner; Thus easier to track/debug.


```suggestion
```

2022-01-03 20:22 UTC, AhmadAlShwaiki commented on src/pages/VerifyPhone/CodeForm/CodeForm.jsx
> +function CodeForm() {
Can we change the name of this component to become only <Form/>
You can use the following suggested file structure.
![image](https://user-images.githubusercontent.com/81982465/147976512-c39d1d7c-6401-4dbe-bb99-e88c88b55fdd.png)

2022-01-03 20:25 UTC, AhmadAlShwaiki commented on src/pages/VerifyPhone/verify-phone.styles.js
> +  font-weight: 600;
Any inherited global styles from `src/styles/global-styles.js` should be removed.

2022-01-03 20:29 UTC, AhmadAlShwaiki commented on src/pages/VerifyPhone/CodeForm/CodeForm.jsx
> +  };
Please remove pure functions like this one outside of the component's function scope.
We should also restraint from using names for such functions and use verbs instead. 
```suggestion
  const renderProgressBar = ({ remainingTime }) => {
    const minutes = Math.floor(remainingTime / 60);
    const seconds = remainingTime % 60;
    return (
      <TimerText>
        {minutes}:{seconds}
      </TimerText>
    );
  };
```

2022-01-03 20:36 UTC, AhmadAlShwaiki requested changes
Changes are mainly concerning the following:
1- duplicate/ unnecessary css properties should be removed.
2- File structure change suggestion.
3- minor linting/ optimization.

2022-01-03 23:24 UTC, abukhadraop commented
@Mahmoudzaid2994, @IbrahimAldereni-socuimtech regarding to this comment https://github.com/abukhadraop-or/reverifi/pull/19#discussion_r777552563
I don't like this way at all, using inline styles or props with values coupled to styles like colors is a bad idea, we use styled-components to handle the styles away from component logic

2022-01-04 00:02 UTC, abukhadraop requested changes

2022-01-04 00:02 UTC, abukhadraop commented on src/pages/VerifyPhone/CodeForm/CodeForm.jsx
> +              onInput={({ target }) => focusNextInput(target)}
```suggestion
              onInput={handleInput}
```

2022-01-04 00:02 UTC, abukhadraop commented on src/pages/VerifyPhone/CodeForm/CodeForm.jsx
> +  };
```suggestion
  const handleInput = ({ target }) => {
    if (!Number.parseInt(target.value, 10)) {
      target.value = '';
      return;
    }
    if (target.nextSibling) {
      target.nextSibling.focus();
    }
  };
```

2022-01-04 00:02 UTC, abukhadraop commented on src/pages/VerifyPhone/CodeForm/CodeForm.jsx
> +        <CancelButton type="button" onClick={() => {}}>
lets remove the empty event handlers

2022-01-04 09:44 UTC, AseelRousan-op commented on src/routes.js
> +    title: 'Verify Phone',
Regarding Mohammad comment below, my bad here the title should be Verify Phone 👍

2022-01-04 14:12 UTC, abukhadraop approved these changes

2022-01-04 14:33 UTC, AhmadAlShwaiki approved these changes

2022-01-04 14:47 UTC, merged