Section 2 - Featured listing
abukhadraop-or/reverifi pull request #2
Opened 2021-12-09 13:25 UTC by IbrahimAldereni-socuimtech

### Description
add Featured listing cards and slider
![Screenshot 2021-12-09 15:24:50](https://user-images.githubusercontent.com/92721815/145404636-cc2e07da-0e46-4869-a37a-0679447cf02c.png)

2021-12-12 11:48 UTC, abukhadraop requested changes
General notes
- we should use rem instead of px as CSS unit except for border width
- as we discussed before each component should have its own directory 
- try to keep react components away from styling and the styled components  away from props as much as possible 
- try to avoid static width and height as much as possible, you can add spacing between elements using margin and padding and you can use min/max-height/width to restrict width and height
- please move all images to assets directory

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/index.jsx
> +import 'slick-carousel/slick/slick-theme.css';
since the carousel styles will be used in other components in the home page please move these imports to `Home`  component

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/index.jsx
> +// import Scrollable from './Scrollable';
Please remove this line

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/index.jsx
> +  const slideBreakPoints = [
this constant will be redefined each time the component rerender while its value never changes, please move it outside the component body

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/index.jsx
> +      breakpoint: 650,
can we use `rem` here?

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/index.jsx
> +      </Scrollable> */}
```suggestion
```

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/index.jsx
> +          dotsClass="slideDots"
```suggestion
          dotsClass="slide-dots"
```

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/featured-listing.styles.js
> +  line-height: 39px;
please avoid changing the line-height unless its really needed, you can use margin and padding to add space around elemnts

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/featured-listing.styles.js
> +export const Flex = styled.div`
i dont see this component used in `index.jsx`

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/featured-listing.styles.js
> +  padding: 11.5px 16px;
please avoid using subpixels, round `11.5` to either `11` or `12` then use `rem`

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/Card.jsx
> +import React from 'react';
this component should have its own directory with its own styles dont mix the styles for multiple components in one styles file

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/Card.jsx
> +import { ReactComponent as BedroomIcon } from '../../assets/icons/bedroom.svg';
we should use absolute imports here and everywhere 
```suggestion
import { ReactComponent as AirConditionerIcon } from 'assets/icons/air-conditioner.svg';
```

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/Card.jsx
> +            lineHeight="22px"
Passing the styles in this way to the styled component is a very bad practice, the whole idea of styled component is to keep react component clean and move all styles to the styled components, try to avoid passing props to styled components unles its really needed, and you can create a new styled component that inherite some styles form another component without passing anything

2021-12-12 11:48 UTC, abukhadraop commented on src/components/FeaturedListing/Scrollable.jsx
> +import React, { useEffect, useRef, useState } from 'react';
look like the implementation with slick-carousel i much easier to understand and maintain, lets remove this file and its styles

2021-12-13 09:34 UTC, IbrahimAldereni-socuimtech commented on src/components/FeaturedListing/index.jsx
> +      breakpoint: 650,
no we can't use any units

2021-12-19 16:45 UTC, Mahmoudzaid2994 commented on src/assets/icons/arrowL.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
please rename this file to `left-arrow.svg`

2021-12-19 16:45 UTC, Mahmoudzaid2994 commented on src/assets/icons/arrowR.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
please rename this file to `right-arrow.svg`

2021-12-19 16:45 UTC, Mahmoudzaid2994 commented on src/components/FeaturedListing/Card/Card.jsx
> +  IconsContainer,
please alphabetize

2021-12-19 16:45 UTC, Mahmoudzaid2994 commented on src/components/FeaturedListing/Card/card.styles.js
> +export const TextMd = styled.p`
please choose a meaningful name

2021-12-19 16:45 UTC, Mahmoudzaid2994 commented on src/components/FeaturedListing/Card/card.styles.js
> +export const TextSm = styled.p`
same here

2021-12-19 16:45 UTC, Mahmoudzaid2994 commented on src/styles/colors.js
> +  black: '#222222',
why you change the black color to `#222222`?

2021-12-19 16:49 UTC, MZeq reviewed
Great job a couple of comments/questions

Can you also add cursor to be pointer when hovering over a button for the navigation/slider list. 

And not sure why the heart/share icons are not centered in the middle of the design but I think that it's your fault

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.jsx
> +import React from 'react';
Please organize your imports, [Check this comment](https://github.com/abukhadraop-or/reverifi/pull/1#discussion_r771961373) for more details.

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.jsx
> +function Card({ data: info }) {
Please use destructuring here instead of using `info.property`, makes the code clean and organized

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.jsx
> +            <Container>
Can we use more descriptive names for the components, `Container`, `Span` , `TextLg`.. etc are a bit generic and don't add semantic value to the page.

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.test.js
> +import React from 'react';
Please use `jsx` extension for React components tests. `.js` is only used for pure `js` files.

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.jsx
> +          <IconContainer stroke="true">
Do you need `="true"` for both of these icons, I think it should work normally if you just pass `stroke`
```suggestion
          <IconContainer stroke>
```

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.test.js
> +import colors from 'styles/colors';
```suggestion
import 'jest-styled-components';
import colors from 'styles/colors';
```

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/Card.test.js
> +    const tree = renderer.create(<Tag />).toJSON();
We only use `enzyme` wrapper native functions, and we don't test css properties. This could be valid only in extreme/rare cases and not on our day to day testing.

please only use `shallow`, `mount` or `render` ..etc and test on the returned wrapper/container.
```suggestion
    const wrapper = shallow(<Tag />);
    wrapper.find(...etc)
```

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/Card/card.styles.js
> +      opacity: 1;
Why was opacity used here?

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/FeaturedListing.test.js
> +    tree = renderer.create(<FeaturedListing />).toJSON();
@abukhadraop Not sure about this type of testing, any ideas if this is used in Hearst applications?

2021-12-19 16:49 UTC, MZeq commented on src/components/FeaturedListing/featured-listing.styles.js
> +        font-size: 0 !important;
We avoid using !important, unless it's really necessary. Are there no workarounds to apply this style?

2021-12-19 16:50 UTC, MZeq commented on src/components/FeaturedListing/Card/card.styles.js
> +      fill: ${({ fill }) => fill && '#fff'};
Can you use all the colors from the colors object. Please double check if you have any loose color values other than this and the one below

2021-12-19 16:51 UTC, MZeq commented on src/styles/colors.js
> +  white: '#fff',
```suggestion
  white: '#ffffff',
```

2021-12-20 08:40 UTC, IbrahimAldereni-socuimtech commented on src/styles/colors.js
> +  black: '#222222',
that's the black color in the design

2021-12-20 09:27 UTC, IbrahimAldereni-socuimtech commented on src/components/FeaturedListing/Card/Card.jsx
> +          <IconContainer stroke="true">
I have this console warning (Warning: Received `true` for a non-boolean attribute `stroke`) if i remove it

2021-12-20 09:54 UTC, IbrahimAldereni-socuimtech commented on src/components/FeaturedListing/Card/card.styles.js
> +      opacity: 1;
because some svgs have opacity = 0.5, so on hover it will be transparent

2021-12-20 10:15 UTC, IbrahimAldereni-socuimtech commented on src/components/FeaturedListing/featured-listing.styles.js
> +        font-size: 0 !important;
I used it because I want to override the default slider styles... but now I remove it and everything is good

2021-12-22 13:29 UTC, MZeq commented on src/components/FeaturedListing/featured-listing.styles.js
> +    outline: 2px solid ${colors.lightgreen};
`outline` is a very important property for accessibility, it's advised to never adjust it or manipulate it for aesthetic purposes..etc.

please remove this line and figure out an alternative solution to highlight the button on focus state.

2021-12-22 16:06 UTC, MZeq approved these changes

2021-12-22 16:10 UTC, abukhadraop approved these changes

2021-12-22 16:27 UTC, MZeq commented
This PR will be closed so we could change, the name of the branch.
The new PR is here https://github.com/abukhadraop-or/reverifi/pull/12#pullrequestreview-838634188

2021-12-22 16:27 UTC, closed without merging