REV-010: Create listing page
abukhadraop-or/reverifi pull request #20
Opened 2021-12-23 17:12 UTC by SaedHalteh

Create the following sections in the Listing Page:
- Offer details
- Slider
- Overview (Description & Claim) 
- Details
- Features
- Location 

Figma links:
Desktop:  https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A10597
Mobile: https://optimumpartners.invisionapp.com/console/share/3V3512T8G6/843334676

2021-12-27 17:33 UTC, AseelRousan-op reviewed
few minor changes

2021-12-27 17:33 UTC, AseelRousan-op commented on src/components/listing-page-components/data.js
> +import image04 from '../../assets/images/slider/abstract04.jpeg';
```suggestion
import image01 from 'assets/images/slider/abstract01.png';
import image02 from 'assets/images/slider/abstract02.jpg';
import image03 from 'assets/images/slider/abstract03.jpg';
import image04 from 'assets/images/slider/abstract04.jpeg';
```

2021-12-27 17:33 UTC, AseelRousan-op commented on src/components/listing-page-components/data.js
> +  },
```suggestion
  icons: {
    airConditioning,
    centralHeating,
    cleaningService,
    diningRoom,
    dryer,
    gym,
    parking,
    sauna,
    swimmingPool,
    tvCable,
    wifi,
  },
```

2021-12-27 20:16 UTC, AseelRousan-op commented on src/assets/images/heart.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#979797" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#979797" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>

```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageDetails/index.jsx
> +      Status: PropTypes.string.isRequired,
```suggestion
      Baths: PropTypes.string.isRequired,
      Beds: PropTypes.string.isRequired,
      Garages: PropTypes.string.isRequired,
      'Home Area': PropTypes.string.isRequired,
      'Lot Dimensions': PropTypes.string.isRequired,
      'Lot area': PropTypes.string.isRequired,
      Rooms: PropTypes.string.isRequired,
      Status: PropTypes.string.isRequired,
      'Year Built': PropTypes.string.isRequired,
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/index.jsx
> +  OverviewSection,
```suggestion
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/index.jsx
> +        <OverviewSection>
```suggestion
        <div>
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/index.jsx
> +        </OverviewSection>
```suggestion
        </div>
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/listing-page-overview.styles.js
> +export const OverviewSection = styled.div``;
```suggestion
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/listing-page-overview.styles.js
> +
```suggestion
export const ClaimButton = styled.button`
  background-color: ${colors.lightgreen};
  border: none;
  border-radius: 1.25rem;
  color: ${colors.white};
  font-size: 1rem;
  font-weight: 600;
  padding: 0.6875rem 0.9375rem 0.5625rem;
  line-height: 1.25rem;

  :hover {
    cursor: pointer;
  }
`;
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/index.jsx
> +          <button type="button"> Claim this property </button>
```suggestion
          <ClaimButton type="button"> Claim this property </ClaimButton>
```

2021-12-28 09:27 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/index.jsx
> +          <button type="button"> Claim this property </button>
I think it would be better if we can create a shared styles file for the listing-page-components to include the base styles of the buttons, for example, they all look the same (`connect`, `claim this property`, `Join Now`,  `submit an offer`,...) and we can inherit this base styled component and override its padding and any different style on each file

2021-12-28 09:37 UTC, AseelRousan-op commented on src/components/listing-page-components/ListingPageOverview/listing-page-overview.styles.js
> +
we need to use the shared `Button` component for all buttons on this page after #16 gets merged, and remove the duplicate styles.

2021-12-30 14:54 UTC, mohdabed123 commented on src/components/listing-page-components/Details/details.styles.js
> +  padding: 1rem 0 0;
are these needed ?

2021-12-30 14:54 UTC, mohdabed123 commented on src/components/listing-page-components/Details/details.styles.js
> +  margin-right: 3.125rem;
do we need this ?

2021-12-30 14:54 UTC, mohdabed123 commented on src/components/listing-page-components/Details/details.styles.js
> +  font-size: 1rem;
does this make any difference?
same thing applies for value font size

2021-12-30 14:54 UTC, mohdabed123 commented on src/components/listing-page-components/Details/details.styles.js
> +  font-weight: 600;
Can we use bold instead of 600 as there is no difference

2021-12-30 14:54 UTC, mohdabed123 commented on src/components/listing-page-components/Features/features.styles.js
> +  }
whats the use of this ? both here and in the details.styles

2021-12-30 14:54 UTC, mohdabed123 commented on src/components/listing-page-components/Features/features.styles.js
> +  padding: 1rem 0 0;
can we also remove these

2021-12-30 14:55 UTC, mohdabed123 commented on src/components/listing-page-components/OfferDetails/index.jsx
> + * @param {String} props.location Asset location.
```suggestion
 * @param {String} price Asset price.
 * @param {String} location Asset location.
```

2022-01-04 13:15 UTC, AhmadAlShwaiki commented on src/assets/images/parking-svgrepo-com (1).svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Please adjust the file name
src/assets/images/parking-svgrepo-com.svg

2022-01-04 17:42 UTC, AseelRousan-op commented on src/components/listing-page-components/Details/details.styles.js
> +import styled from 'styled-components';
Can modify the directory name here to be listing-page instead of listing-page-components since its already in the components directory

2022-01-04 17:42 UTC, AseelRousan-op commented on src/components/listing-page-components/Details/details.styles.js
> +  border-bottom: 1px solid ${colors.midGrey};
can we use rem here

2022-01-04 17:42 UTC, AseelRousan-op commented on src/components/listing-page-components/OfferDetails/index.jsx
> + * @param {String} props.location Asset location.
```suggestion
 * @param {Object} props          The component props.
 * @param {String} props.price    Asset price.
 * @param {String} props.location Asset location.
```

2022-01-04 17:42 UTC, AseelRousan-op commented on src/components/listing-page-components/OfferDetails/index.jsx
> +          padding="0"
why we're using inline styles here? and not adding them to the LogoButton styled component itself, 
the same comment apply on the following two LogoButtons

2022-01-04 17:42 UTC, AseelRousan-op commented on src/components/listing-page-components/Overview/index.jsx
> +            padding="0.6875rem 0.9375rem 0.5625rem"
same here

2022-01-04 17:42 UTC, AseelRousan-op commented on src/components/listing-page-components/Overview/overview.styles.js
> +  border: 1px solid ${colors.midGrey};
to use rem across all the border-styles, please

2022-01-04 21:01 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Details/index.jsx
> +    <MainContainer>
```suggestion
    <Container>
```

2022-01-04 21:01 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Details/index.jsx
> +      <DetailsContainer>
```suggestion
      <Wrapper>
```

2022-01-04 21:26 UTC, AhmadAlShwaiki commented on package-lock.json
> +    "node_modules/jquery": {
Can you please remove these changes from the commit, since there is no change on the package.json

2022-01-04 21:33 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/OfferDetails/index.jsx
> +    <OfferDetailsContainer>
```suggestion
    <Container>
```

2022-01-04 21:44 UTC, AhmadAlShwaiki commented on src/pages/ListingPage.jsx
> +    <div>
```suggestion
```

2022-01-04 21:51 UTC, AhmadAlShwaiki commented on src/pages/ListingPage.jsx
> +      <OfferDetails price={price} location={location} />
```suggestion
      <OfferDetails data={{price, location}} />
```

2022-01-04 22:00 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/OfferDetails/index.jsx
> +            type="button"
```suggestion
          <Button
            aria-label="Submit an Offer"
            borderRadius="1.25rem"
            fontSize="1rem"
            type="button"
```

2022-01-04 22:03 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/OfferDetails/offer-details.styles.js
> +  justify-content: center;
Please clean up css where not needed.
```suggestion
```

2022-01-04 22:08 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/OfferDetails/offer-details.styles.js
> +`;
Cant see why do we need these components?
```suggestion
```

2022-01-04 22:10 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Overview/index.jsx
> +          </p>
props for using simple html elements here where possible 👍

2022-01-04 22:13 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Overview/index.jsx
> +function Overview({ statistics, overview }) {
less props that serve one goal = easier to read and use the component
```suggestion
function Overview({data }) {
```

2022-01-04 22:39 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Overview/index.jsx
> +      <FormContainer>
The Form living inside the overview doesn't make any sense, Can you please remove it from here into the main listing page?

2022-01-04 22:41 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Overview/overview.styles.js
> +export const FormContainer = styled.div`
Cant find a huge difference between this component and the following:
Claim
ScheduleVisit
They all seem to be doing the same thing which is render a header and a piece of text.
Please dedup them into one component.

2022-01-05 08:08 UTC, SaedHalteh commented on src/components/listing-page-components/Details/details.styles.js
> +  border-bottom: 1px solid ${colors.midGrey};
I thought we are using px for border width in order to be more consistent, as I recieved a previous comment to convert border width to px instead of rem? So should I convert all border width to use px or should I keep them in rem ??

2022-01-05 08:14 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Overview/overview.styles.js
> +  border-right: 1px solid ${colors.gray};
```suggestion
  border-right: 1px solid ${colors.midGrey};
```

2022-01-05 08:14 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Overview/overview.styles.js
> +  `};
Is this needed?
```suggestion
```

2022-01-05 08:16 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/SimilarListings/index.jsx
> +function SimilarListings({ similarListings }) {
```suggestion
function SimilarListings({ data }) {
```

2022-01-05 08:29 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/SimilarListings/index.jsx
> +          <Slider
Please add more cards in the slider for it's demo, not sure you need to pass all these props

2022-01-05 08:32 UTC, AhmadAlShwaiki commented on src/components/listing-page-components/Slider/slider.styles.js
> +export const Previous = styled.div`
dedupe into one please.
```suggestion
export const Arrow = styled.div`
```

2022-01-05 08:32 UTC, AhmadAlShwaiki commented on src/components/shared/Button/Button.style.js
> +  font-size: ${(props) => props.fontSize || '0.75rem'};
```suggestion
  font-size: ${({ fontSize }) =>fontSize || '0.75rem'};
```

2022-01-05 08:33 UTC, AhmadAlShwaiki requested changes
Please recheck all comments left for the components grouping and css clean up

2022-01-09 14:47 UTC, AseelRousan-op approved these changes
Approving this in advance, very minor Change otherwise looks good !

2022-01-09 14:47 UTC, AseelRousan-op commented on src/components/listing-page/Details/index.jsx
> +  const { details } = data;
I see you're passing the data.details directly, so you can get the details only  
```suggestion
function Details({ details }) {
```

2022-01-09 14:48 UTC, AhmadAlShwaiki approved these changes

2022-01-09 15:32 UTC, mohdabed123 approved these changes

2022-01-09 17:04 UTC, merged