REV-009: create agent list page
abukhadraop-or/reverifi pull request #22
Opened 2021-12-27 11:59 UTC by RaniaSAloun

Created agent list page with the following changes:

- created agent card as a shared component in an added common folder
- created AgentCardsContainer which holds the agent cards as a component
- created AgentsListBanner component holding the heading and the filter bar
- added the new page's route to the routes file
- added desktopExtraMax as a new breakpoint

Slide pages:
Desktop: https://optimumpartners.invisionapp.com/console/share/2Y34DAX6RD/812252250
Mobile: https://optimumpartners.invisionapp.com/console/share/3V3512T8G6/843334662

2021-12-29 06:02 UTC, Mahmoudzaid2994 commented on src/assets/icons/like.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather fea
please add an empty line at the end of each file.

2021-12-29 06:04 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/agent-cards-container.styles.js
> +    max-width: 79rem;
Could you order these props alphabetically

2021-12-29 06:06 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/index.jsx
> +
Please add documentation for any function
```suggestion

  // fetch agent data
```

2021-12-29 06:13 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/index.jsx
> + */
```suggestion
/**
 * Component holding the cards of agents, it maps agents to their cards.
 *
 * @param {array} filteredTarget Filtered target array.
 *
 * @return {JSX.Element} Container holding agent cards.
 */
```

2021-12-29 06:13 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/index.jsx
> +  filteredTarget: PropTypes.string.isRequired,
```suggestion
  filteredTarget: PropTypes.arrayOf.isRequired,
```

2021-12-29 06:20 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/agents-list-banner.styles.js
> +export const FilterTxt = styled.p`
change the name to FilterText and also please change it at the components where use it

2021-12-29 06:20 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/agents-list-banner.styles.js
> +export const SearchBtn = styled.button`
change the name to SearchButton and also please change it at the components where use it

2021-12-29 06:21 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/index.jsx
> + *
add documentation for filter props

2021-12-29 06:22 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/index.jsx
> +
add documentation for this function and also for all functions please

2021-12-29 06:26 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/index.jsx
> +  };
```suggestion
  const handleAddressFilter = (event) => {
    filter(event.target.value);
  };
```

2021-12-29 06:26 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/index.jsx
> +
```suggestion

```

2021-12-29 06:28 UTC, Mahmoudzaid2994 commented on src/components/shared/AgentCard/agent-card.styles.js
> +
use this SVG's directly at the component
```suggestion

```

2021-12-29 06:35 UTC, Mahmoudzaid2994 commented on src/components/shared/AgentCard/index.jsx
> + * @param {number} props.phoneNumber Contact number of agent.
```suggestion
 * @param {Object} props               Props passed to AgentCard.
 * @param {string} props.address       Agent's address.
 * @param {string} props.agentName     Agent's name.
 * @param {string} props.companyName   Agent's company name.
 * @param {string} props.email Contact Agent's email.
 * @param {number} props.phoneNumber   Agent's contact number.
```

2021-12-29 06:41 UTC, Mahmoudzaid2994 commented
For the Images, I think we should move them to Image folder and also use kabab case for naming

2021-12-30 16:21 UTC, AseelRousan-op commented on src/components/AgentCardsContainer/AgentCard/agent-card.styles.js
> +  font-style: normal;
we can remove this style from all the components
```suggestion
```

2021-12-30 16:21 UTC, AseelRousan-op commented on src/components/AgentCardsContainer/AgentCard/agent-card.styles.js
> +  mix-blend-mode: normal;
the default mix-belnd-mode is normal, I think we can also remove this 
```suggestion
```

2021-12-30 16:41 UTC, AseelRousan-op reviewed
Looks good few small styles changes

2021-12-30 16:41 UTC, AseelRousan-op commented on src/components/AgentsListBanner/agents-list-banner.styles.js
> +  border: none;
```suggestion
```

2021-12-30 16:41 UTC, AseelRousan-op commented on src/components/AgentsListBanner/agents-list-banner.styles.js
> +  margin: 0;
```suggestion
```

2021-12-30 16:41 UTC, AseelRousan-op commented on src/components/AgentsListBanner/agents-list-banner.styles.js
> +  padding: 0;
```suggestion
```

2022-01-03 13:42 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/AgentCard/agent-card.styles.js
> +    width: 37.5rem;
```suggestion
  ${mq.desktop`
    flex-direction: row;
```

2022-01-03 13:44 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/agent-cards-container.styles.js
> +
```suggestion

export const Wrapper = styled.div`
  padding: 1rem;

  ${mq.desktop`
   flex: 0 0 50%;
   max-width: 50%;
  `};
`;

```

2022-01-03 13:44 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/agent-cards-container.styles.js
> +  `};
```suggestion
   ${mq.desktop`
    display: flex;
    flex-wrap: wrap;
    max-width: 79rem; 
    padding: 0.5rem;
  `};
```

2022-01-03 13:45 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/index.jsx
> +import { CardsContainer, Container } from './agent-cards-container.styles';
```suggestion
import {
  CardsContainer,
  Container,
  Wrapper,
} from './agent-cards-container.styles';```

2022-01-03 13:46 UTC, Mahmoudzaid2994 commented on src/components/AgentCardsContainer/index.jsx
> +          />
```suggestion
          <Wrapper>
            <AgentCard
              address={agent.address}
              agentImg={agent.agentImg}
              agentName={agent.agentName}
              companyName={agent.companyName}
              email={agent.email}
              key={agent.id}
              phoneNumber={agent.phoneNumber}
            />
          </Wrapper>
```

2022-01-03 13:50 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/index.jsx
> +import { useMediaQuery } from '@material-ui/core';
Remove `material-ui` and handle the display for desktop or mobile using css

2022-01-03 13:51 UTC, Mahmoudzaid2994 commented on src/components/AgentsListBanner/index.jsx
> +                <AgentSearch placeholder="Agent's Name" />
use shared input

2022-01-03 13:51 UTC, Mahmoudzaid2994 commented on src/styles/breakpoints.js
> +
```suggestion

```

2022-01-05 08:48 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/index.jsx
> +  phoneNumber,
```suggestion
data
```

2022-01-05 08:49 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/index.jsx
> +              onClick={() => {}}
```suggestion
```

2022-01-05 08:53 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/index.jsx
> +        <HeartButton
```suggestion
        <RoundedButton
```

2022-01-05 08:55 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/agent-card.styles.js
> +export const HeartButton = styled(Button)`
```suggestion
export const HeartButton = styled(RoundedButton)`
```

2022-01-05 09:00 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/agent-card.styles.js
> +  width: 1.125rem;
```suggestion
  width: 1rem;
```

2022-01-05 09:06 UTC, RaniaSAloun commented on src/components/AgentsListBanner/index.jsx
> +                <AgentSearch placeholder="Agent's Name" />
the shared input is not suitable for the filter component

2022-01-05 09:07 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/agent-card.styles.js
> +`;
```suggestion
export const IconContainer = styled.div`
  display: flex;

  > svg {
    width: 1rem;
    margin: 0.5rem;
  }
`;
```

2022-01-05 09:08 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/index.jsx
> +            </IconContainer>
```suggestion
            <IconContainer>
              <MailIcon />
              <PhoneIcon />
            </IconContainer>
```

2022-01-05 09:22 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentsListBanner/agents-list-banner.styles.js
> +export const AgentSearch = styled.input`
Use only one component please
```suggestion
export const SearchTag = styled.input`
```

2022-01-05 09:52 UTC, AhmadAlShwaiki commented on src/pages/AgentList.jsx
> +      <AgentCardsContainer />
```suggestion
  const [agents, setAgents] = useState([]);

  /**
   * Fetches agents data from API and sets it to agents state.
   */
  useEffect(() => {
    const fetchAgents = async () => {
      const data = await getAgents();
      setAgents(data);
    };
    fetchAgents();
  });

  return (
    <Container>
      <CardsContainer>
        {agents.map((agent) => (
          <Wrapper key={agent.id}>
            <AgentCard
              address={agent.address}
              agentImg={agent.agentImg}
              agentName={agent.agentName}
              companyName={agent.companyName}
              email={agent.email}
              phoneNumber={agent.phoneNumber}
            />
          </Wrapper>
        ))}
      </CardsContainer>
    </Container>

```

2022-01-05 09:53 UTC, AhmadAlShwaiki requested changes
components grouping and css cleanup

2022-01-09 14:52 UTC, AhmadAlShwaiki commented on src/components/agent-list/AgentCard/agent-card.styles.js
> +export const FooterButtonsContainer = styled.div`
```suggestion
export const FooterButtonsContainer = styled(ButtonsContainer)`
  align-items: center;
```

2022-01-09 14:56 UTC, AhmadAlShwaiki approved these changes
small change requested, looks good.

2022-01-09 15:05 UTC, AseelRousan-op approved these changes

2022-01-09 15:22 UTC, mohdabed123 approved these changes
LGTM

2022-01-09 15:22 UTC, AhmadAlShwaiki approved these changes

2022-01-09 20:21 UTC, merged