REV-299-search listing page
abukhadraop-or/reverifi pull request #225
Opened 2022-03-13 15:48 UTC by IbrahimAljabrST

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-299

### Description

add map to search page when no results

2022-03-14 09:01 UTC, mohdabed123 requested changes

2022-03-14 09:01 UTC, mohdabed123 commented on src/components/listing-search-page/SearchHeader/index.jsx
> +  };
these are duplicated in more than one file , can you make them shared functions and constants in utils files

2022-03-14 10:14 UTC, IbrahimAljabrST commented on src/components/home/Storyboard/index.jsx
> +    componentRestrictions: { country: ['us'] },
this for google maps auto complete, we cant change the name

2022-03-17 12:50 UTC, mohdabed123 approved these changes

2022-03-17 12:50 UTC, merged