REV-013: create-listing-page-form-and-schedule-visit-component
abukhadraop-or/reverifi pull request #23
Opened 2021-12-27 15:21 UTC by Anas-AlRamahi

### Description
Added contact form & schedule visit sections of listings page.

links: 
[Revirifi Design](https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A1)
[Revirifi Excel Sheet](https://docs.google.com/spreadsheets/d/1o7cWWsGAgbzCfvuCwblf2ExczTyPkWbfx2UhRbEpRLo/edit#gid=0)

2021-12-30 09:30 UTC, mohdabed123 commented on src/pages/Home.jsx
> -
Can wee add the space back

2021-12-30 10:13 UTC, mohdabed123 commented on src/components/ScheduleVisit/index.jsx
> +          </DateCard>
Can we not hardcode this, maybe create mock data

2021-12-30 10:41 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +  background: ${colors.white};
is this needed

2021-12-30 10:42 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +  border-radius: 0.56rem;
can we use px instead of rem for borders and border-radius

2021-12-30 11:06 UTC, Anas-AlRamahi commented on src/components/ContactForm/contact-form.styles.js
> +  background: ${colors.white};
not really, I will remove it

2021-12-30 11:15 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +`;
can we remove this and just use div instead

2021-12-30 11:15 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +
just keep the margin remove everything else

2021-12-30 11:15 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +`;
can you we remove this and used the shared button component

2021-12-30 11:15 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +
same thing here

2021-12-30 12:37 UTC, Anas-AlRamahi commented on src/components/ContactForm/contact-form.styles.js
> +  align-items: center;
yes, when it is on smaller than mobile width, it will center the name in the middle for more convenience.

2021-12-30 12:47 UTC, Anas-AlRamahi commented on src/components/ContactForm/contact-form.styles.js
> +  align-items: center;
Yes, when it is less than mobile width, it will center everything horizontally.

2021-12-30 12:53 UTC, mohdabed123 commented on src/components/ContactForm/contact-form.styles.js
> +`;
is this needed?

2021-12-30 13:30 UTC, Anas-AlRamahi commented on src/components/ContactForm/contact-form.styles.js
> +
This is needed when the screen size is less than mobile, and the name's width is less than dial button's.

2021-12-30 15:12 UTC, mohdabed123 commented on src/assets/date-picker.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x=
add a new line

2021-12-30 15:12 UTC, mohdabed123 commented on src/components/ScheduleVisit/index.jsx
> +          responsive={[
can we create a constant out side the component that has these values 
```suggestion
          responsive={responsive}
```

2021-12-30 15:12 UTC, mohdabed123 commented on src/components/ContactForm/index.jsx
> +import * as yup from 'yup';
import { string, number, object } from 'yup';

2021-12-30 15:12 UTC, mohdabed123 commented on src/components/ContactForm/index.jsx
> +        <Input {...register('phoneNumber')} placeholder="Phone Number" />
can we make this to accept numbers only

2022-01-05 10:06 UTC, AhmadAlShwaiki commented on src/components/ContactForm/index.jsx
> +        <ErrorMessage>{errors.phoneNumber?.message}</ErrorMessage>
Please use a friendly error message
```suggestion
        <ErrorMessage>Phone number is a required field</ErrorMessage>
```

2022-01-05 10:10 UTC, AhmadAlShwaiki commented on src/components/ContactForm/index.jsx
> +  phoneNumber: number().required(),
I can enter negative numbers, please use proper phone validation.
hint: https://stackoverflow.com/questions/52483260/validate-phone-number-with-yup

2022-01-05 10:19 UTC, AhmadAlShwaiki commented on src/components/ContactForm/contact-form.styles.js
> +`;
```suggestion
export const ErrorMessage = styled.span`
  color: ${colors.red};
  font-size: 0.75rem;
`;
```

2022-01-05 10:41 UTC, AhmadAlShwaiki commented on src/components/ScheduleVisit/index.jsx
> +  const responsive = [
Remove outside the component please
```suggestion
```

2022-01-05 10:43 UTC, AhmadAlShwaiki commented on src/components/ScheduleVisit/index.jsx
> +      <Title>Schedule Visit</Title>
I see this component used everywhere in the app, please convert it to a shared component
![image](https://user-images.githubusercontent.com/81982465/148204664-7e786748-929c-4e1b-acd8-a60cd2155ea5.png)

2022-01-05 10:56 UTC, AhmadAlShwaiki requested changes
general components optimizations and css fixes

2022-01-06 09:39 UTC, mohdabed123 approved these changes

2022-01-06 10:03 UTC, AhmadAlShwaiki commented on src/components/ScheduleVisit/index.jsx
> +          {data.map((item) => (
```suggestion
          {data.map(( { date, day } ) => (
```

2022-01-06 10:03 UTC, AhmadAlShwaiki approved these changes

2022-01-11 13:31 UTC, Mahmoudzaid2994 commented
Just some notes:
- change all `px` to `rem`
- call the new components at `listing page`
- change the `Description` as we discuss

2022-01-11 21:04 UTC, AseelRousan-op approved these changes
one question here, if we can remove these negative styles, otherwise looks very good 👍

2022-01-11 21:04 UTC, AseelRousan-op commented on src/components/listing-page/ScheduleVisit/schedule-visit.styles.js
> +    left: -1.37rem;
do we need this negative left here, I can't see a big difference in removing it? and the same question for the right style added to the slick next

2022-01-12 09:50 UTC, Mahmoudzaid2994 commented on src/components/listing-page/ContactForm/index.jsx
> +/* eslint-disable react/jsx-props-no-spreading */
```suggestion

```

2022-01-12 09:57 UTC, Mahmoudzaid2994 commented on src/components/listing-page/ScheduleVisit/index.jsx
> +/* eslint-disable react/prop-types */
```suggestion

```

2022-01-12 09:58 UTC, Mahmoudzaid2994 commented on src/components/listing-page/ScheduleVisit/index.jsx
> +import { ReactComponent as DateIcon } from 'assets/date-picker.svg';
```suggestion
import { ReactComponent as DateIcon } from 'assets/date-picker.svg';
import PropTypes from 'prop-types';
```

2022-01-12 09:58 UTC, Mahmoudzaid2994 commented on src/components/listing-page/ScheduleVisit/index.jsx
> +
```suggestion

CustomInput.propTypes = {
  onClick: PropTypes.function.isRequired,
  value: PropTypes.string.isRequired,
};

```

2022-01-12 10:04 UTC, Mahmoudzaid2994 commented on src/components/listing-page/ContactForm/index.jsx
> +}).required();
Move the schema to `ContactForm/contact-form.js` than import it to this component

2022-01-12 11:27 UTC, Mahmoudzaid2994 approved these changes

2022-01-12 11:27 UTC, merged