update completed pages the confirmed images
abukhadraop-or/reverifi pull request #235
Opened 2022-03-17 16:11 UTC by FarahJamal-business

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-397

### Description

Update some new confirmed characters

2022-03-19 10:29 UTC, mohdabed123 requested changes

2022-03-19 10:29 UTC, mohdabed123 commented on src/components/agent-list/ResultNotFound/index.jsx
> +
the indentation here needs to be fixed using prettier formatter

2022-03-19 10:29 UTC, mohdabed123 commented on src/components/agent-list/ResultNotFound/result.styles.js
> +  font-size:32px;
```suggestion
  font-size:32px;
```

we use rem instead of px , please change this to rem instead , 
looks like some one used a div to hold a only a text so can you please fix and use a heading instead of a div.

2022-03-19 10:29 UTC, mohdabed123 commented on src/components/agent-list/ResultNotFound/result.styles.js
> +  font-style:Montserrat;
```suggestion
  font-style:inherit;
```

2022-03-20 08:31 UTC, mohdabed123 commented on src/components/agent-list/ResultNotFound/result.styles.js
> +  font-weight: 600;
padding: 2rem 2rem 4rem 2rem;
  text-align: center;
  width: 80%;
  font-style: inherit;

2022-03-20 11:01 UTC, MohammadKayyali approved these changes

2022-03-20 11:02 UTC, merged