REV-119 Forgot Password finished front-end
abukhadraop-or/reverifi pull request #244
Opened 2022-03-20 09:56 UTC by FarahJamal-business

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-119

2022-03-20 11:48 UTC, mohdabed123 reviewed
Some initial comments 
also please apply formatting in all files

2022-03-20 11:48 UTC, mohdabed123 commented on src/components/reset-password/index.jsx
> +console.log(showModal);
```suggestion

```

2022-03-20 11:48 UTC, mohdabed123 commented on src/components/reset-password/index.jsx
> +                      height: '3rem',
use a styled component and export it

2022-03-20 11:48 UTC, mohdabed123 commented on src/components/reset-password/index.jsx
> +          console.log(error);
remove all console logs and create a file in services folder to hit this end-point , this will probably fail in QA

2022-03-20 11:48 UTC, mohdabed123 commented on src/components/reset-password/reset-password-modal.styles.js
> +    `}
you are using the same font size in both mobile and  tablet+ 
also headings can adjust their size accordingly so there is no need to set the font-size 
font-weight is also not need since headings are bold by default

2022-03-20 11:48 UTC, mohdabed123 commented on src/components/reset-password/reset-password-modal.styles.js
> +  line-height: 21.94px;
```suggestion
  font-family: inherit;
  line-height: 1.4rem;
```

2022-03-23 14:38 UTC, mohdabed123 requested changes

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/shared/Accordion/accordion.styles.js
> +    margin-top: 0.938rem;
please refrain from changing styles of a shared component 
if you want to change the styles use styled components like this
const newAccordion = styled(Accordion)`
margin-top: 0.93rem;
`;

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/shared/Button/Button.style.js
> +  border: 0.063rem solid ${colors.gray};
same thing here

2022-03-23 14:38 UTC, mohdabed123 commented on src/contexts/NestedModalsContext/index.jsx
> +
use the shared modal you can ask @IbrahimAldereni-socuimtech

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/reset-password-email/index.jsx
> +                {' '}
```suggestion
```

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/reset-password-email/reset-password-email-modal.styles.js
> +`;
```suggestion
`;

```

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/reset-password-email/reset-password-email-modal.styles.js
> +  line-height: 1.371rem;
is there a reason to change the line-height

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/reset-password-email/reset-password-email-modal.styles.js
> +`;
```suggestion
`;

```

2022-03-23 14:38 UTC, mohdabed123 commented on src/components/reset-password/index.jsx
> +  };
```suggestion
  };
  
```

2022-03-23 14:38 UTC, mohdabed123 commented on src/pages/Login.jsx
> +  );
there is already a login page

2022-03-23 14:38 UTC, mohdabed123 commented on src/pages/ChangePasswordP.jsx
> +function ChangePasswordP() {
```suggestion
function ChangePassword() {
```

2022-03-23 14:38 UTC, mohdabed123 commented on src/pages/ChangePassword/change-password.styles.js
> +`;
```suggestion
`;

```

2022-03-23 14:38 UTC, mohdabed123 commented on src/pages/ChangePassword/change-password.styles.js
> +`;
```suggestion
`;

```

2022-03-23 15:42 UTC, FarahJamal-business commented on src/routes.js
> +    component: lazy(() => import('pages/Login')),
because I need to use Modal here So I have asked dev team here they said create new file and wrap it with modal provider

2022-03-23 15:46 UTC, FarahJamal-business commented on src/contexts/NestedModalsContext/index.jsx
> +
It didn't worked for me to open modal from another modal with their shared one

2022-03-23 15:46 UTC, FarahJamal-business commented on src/contexts/ShareResetLinkContext/index.jsx
> +  );
same here I want to share link between modal and page so I have to use this their shared one doesn't worked

2022-03-23 15:47 UTC, FarahJamal-business commented on src/components/reset-password-email/reset-password-email-modal.styles.js
> +  line-height: 1.371rem;
no I just follow figma design

2022-03-29 14:21 UTC, closed without merging