REV-017-create-listing-search-page
abukhadraop-or/reverifi pull request #27
Opened 2021-12-28 16:32 UTC by Ibrahim-aljabr-sociumtech

![listing searhc page](https://user-images.githubusercontent.com/96583952/147586830-41242736-2584-4855-b623-3e700d241ea2.png)

- figma link:
https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A15651

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/index.jsx
> + */
```suggestion
/**
 * Render location search input.
 *
 * @param  {any} leftElement add description here
 * @param  {any} rightElement add description here
 * @param  {string} size add description here
 * @param  {string} placeholder add description here
 *
 * @return {JSX.Element}
 */
```

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/index.jsx
> +
```suggestion
```

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  box-shadow: 0rem 0.0625rem 0.1875rem ${colors.mineShaft}29;
alphabetize

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  `,
```suggestion
  `,
  
```

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  background-color: transparent;
is this needed

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  flex: 1;
can we remove this

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  background-color: ${colors.white};
is this needed

2021-12-30 16:22 UTC, mohdabed123 commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  justify-content: space-evenly;
can we remove this

2021-12-30 16:22 UTC, mohdabed123 commented on src/pages/ListingSearch/Map/map.style.js
> +  `}
```suggestion

  ${mq.tabletWide`
      display: block;
      flex:0.8;
      max-height:55rem;
  `}
  
  ${mq.desktop`
      flex:1;
  `}
  
  ${mq.desktopMax`
      flex:1.5;
  `}
```

2021-12-30 16:22 UTC, mohdabed123 commented on src/pages/ListingSearch/SearchResults/Card/card.style.js
> +
can we add spaces between styled components here

2021-12-30 16:51 UTC, IbrahimAljabrST commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  background-color: transparent;
yes needed

2022-01-05 11:07 UTC, AhmadAlShwaiki commented on src/pages/ListingSearch/Map/map.style.js
> +      max-height:55rem;
Is this needed?
```suggestion
```

2022-01-05 11:09 UTC, AhmadAlShwaiki commented on src/pages/ListingSearch/Map/map.style.js
> +      max-height:55rem;
Can you please recheck and remove any unneeded css property?
```suggestion
```

2022-01-05 11:13 UTC, AhmadAlShwaiki commented on src/pages/ListingSearch/SearchResults/Card/card.style.js
> +  border-radius: 8px;
Please convert to pxs

2022-01-05 11:27 UTC, AhmadAlShwaiki commented on src/pages/ListingSearch/SearchResults/listing-search-cards.style.js
> +  button:nth-child(2) {
Please convert this to the shared styled component `src/components/shared/Button/index.jsx`

2022-01-05 11:28 UTC, AhmadAlShwaiki commented on src/pages/ListingSearch/SearchResults/listing-search-cards.style.js
> +    }
Please convert this to the shared styled component src/components/shared/Button/index.jsx


```suggestion
```

2022-01-05 12:34 UTC, AhmadAlShwaiki requested changes
Please remove any unneeded css and use existing shared components wherever possible.

2022-01-11 15:04 UTC, Mahmoudzaid2994 commented
Please fix this error 
![Screen Shot 2022-01-11 at 4 55 32 PM](https://user-images.githubusercontent.com/58739087/148967305-5263df71-939b-4904-a853-c629162e678a.png)

2022-01-12 09:03 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/listing-search-cards.style.js
> +  svg {
```suggestion

  svg {
```

2022-01-12 09:04 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/SearchResults/listing-search-cards.style.js
> +  button {
Please use styled component here
```suggestion
```

2022-01-12 09:18 UTC, AhmadAlShwaiki commented on src/components/shared/LocationSearchInput/index.jsx
> + * @param  {string} size add the size for the input sm,md,lg
Do we really need these props?
```suggestion
```

2022-01-12 09:18 UTC, AseelRousan-op reviewed
@IbrahimAljabrST Do we need to add the footer at the end of this page, instead of the blank white space?

2022-01-12 09:49 UTC, Mahmoudzaid2994 approved these changes

2022-01-12 10:05 UTC, IbrahimAljabrST commented on src/components/shared/LocationSearchInput/index.jsx
> + * @param  {string} size add the size for the input sm,md,lg
yes for the the other pages design

2022-01-12 11:32 UTC, AhmadAlShwaiki approved these changes
Looks good

2022-01-12 11:33 UTC, AhmadAlShwaiki commented on .vscode/settings.json
> +{
Please add .vscode to gitignore 🙏 
```suggestion
```

2022-01-13 10:53 UTC, AseelRousan-op approved these changes

2022-01-16 11:36 UTC, MZeq requested changes
Good job, the map seems to be semi functional but I have a couple of notes
- The height of the body is not filling the whole page, this is an issue that can be addressed in a different PR, so you don't have to worry about it for now.
- We should use the Shared components and not create our own, keep the ones you created for now but add a TODO as a comment to remove them and adjust the shared components to support that functionalities that you're looking for.
- We can't add packages or install anything unless it's 100% necessary and approved, and we have to pay attention on whether these are project or dev dependencies.
- Adjusting the SVGs from inside the .svg files is not advised, this would make them un-reusable, please remove the properties that you want to adjust and style them where they are used.

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/ListingSearch/index.jsx
> +/**
```suggestion
];

/**
 * renderCards component.
 *
 * @param {Object} data to render card on map.
 *
 * @return {JSX.Element}
 */
function renderCards({ data }) {
  return <MapCard data={data} lng={data} lat={data} />;
}
/**
```

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/ListingSearch/listing-search.style.js
> +    flex:1.5;
```suggestion
    flex: 1;
`}

  ${mq.desktopMax`
    flex: 1.5;
```

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/Card/card.style.js
> +  overflow: hidden;
```suggestion
```
I don't believe that this is needed.

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/Card/card.style.js
> +  max-height: 8.5rem;
```suggestion
```
I don't believe that this is needed.

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/Card/card.style.js
> +  min-width: 100%;
```suggestion
  height: 100%;
  width: 100%;
```

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/Card/card.style.js
> +      margin:1rem 0;
```suggestion
    font-size:1.125rem;
    font-weight: 500;
    margin:1rem 0;
```

fix the indentation here.

2022-01-16 11:36 UTC, MZeq commented on src/components/listing-search-page/SearchResults/listing-search-cards.style.js
> +export const FilterButton = styled.button`
I believe we should use the shared button instead of creating a new one, and can you please adjust the cursor to be pointer.

2022-01-16 12:30 UTC, MZeq commented on src/components/listing-search-page/Card/card.style.js
> +  overflow: hidden;
```suggestion
```
I don't believe that this needed.

2022-01-16 12:58 UTC, IbrahimAljabrST commented on src/components/shared/LocationSearchInput/search-input.style.js
> +export const StyledInput = styled.input`
This component using google api key to get places, malek want it to be a shared component

2022-01-16 13:01 UTC, IbrahimAljabrST commented on src/components/shared/LocationSearchInput/search-input.style.js
> +  outline: none;
I took the same input Abu Khadra made to look the same

2022-01-16 13:20 UTC, IbrahimAljabrST commented on src/assets/icons/filter.svg
> -<?xml version="1.0" encoding="iso-8859-1"?>
This is how figma export it, I have change the style from the style component

2022-01-16 15:05 UTC, MZeq approved these changes

2022-01-16 15:07 UTC, MZeq commented
LGTM, just remove the outline:none and this looks like it's good to go.

2022-01-16 15:29 UTC, AhmadAlShwaiki commented on .gitignore
> +
```suggestion
```

2022-01-16 15:42 UTC, AhmadAlShwaiki commented on src/components/listing-search-page/ListingSearch/index.jsx
> +    price: '$750-$800',
```suggestion
    price: '750-800',
```
In case new currency is added.

2022-01-19 14:31 UTC, merged