Anas
abukhadraop-or/reverifi pull request #3
Opened 2021-12-09 14:31 UTC by Anas-AlRamahi

### Description
Finished implementing the frontend design for reverifiPlus and exploreListings sections in HomePage

2021-12-12 15:07 UTC, abukhadraop requested changes
General notes
- please pay attention to the app console errors
- there is no need to suffixe the styled components names with elemnt type (ex `Div`)
- try to use meaningful names for the styled components (ex `SliderDiv`=>`SliderContainer`) 
- keep in mind the lees code to achieve the result is the better, always try to enhance you code after you wrote it

2021-12-12 15:07 UTC, abukhadraop commented on src/components/ExploreListing/explore-listing.styles.js
> +export const FirstImgListings = styled.p`
the `p` tag is usually used with paragraphs

2021-12-19 16:33 UTC, Mahmoudzaid2994 commented on src/components/ReverifiPlus/reverifi-plus.styles.js
> +export const PlusUpperSection = styled.div`
same here and for the rest variables

2021-12-19 16:33 UTC, Mahmoudzaid2994 commented on src/components/ReverifiPlus/reverifi-plus.styles.js
> +export const ReverifiPlusContainer = styled.div`
please choose a meaningful name for variables

2021-12-19 16:33 UTC, Mahmoudzaid2994 commented on src/components/ReverifiPlus/index.jsx
> +    <ReverifiPlusContainer>
for this div the style `justify-content` should be `space-between` and also add margin on left and right

2021-12-19 16:33 UTC, Mahmoudzaid2994 commented on src/components/ExploreListing/explore-listing.styles.js
> +    height: 36.8px;
Please convert px to rem

2021-12-19 16:33 UTC, Mahmoudzaid2994 commented on src/assets/Shape.svg
> +<svg width="32" height="28" viewBox="0 0 32 28" fill="none" xmlns="http://www.w3.org/2000/svg">
please change the names of all SVGs to be kebab case.

2021-12-20 08:37 UTC, Anas-AlRamahi commented on src/components/ReverifiPlus/index.jsx
> +    <ReverifiPlusContainer>
For this one I used a predefined media query, should I commit changes? or is there a better way to implement it?

2021-12-22 13:21 UTC, MZeq commented
Can you rename all the images to be brief and descriptive of the shape?

`new-york-city-evening-NYCTG0221(3).jpg` is too long and contains unnecessary sections.
`newyork` or `newyork-city` is a more appropriate and descriptive name.

Same thing for all the SVGs.

`agent-svgrepo-com.svg` the name doesn't describe the shape of the image and `svgrepo-com` is not wanted. 
and `shape` .. etc

2021-12-22 13:22 UTC, MZeq commented on src/components/ExploreListing/explore-listing.styles.js
> +  & .slick-slider {
if we could remove the `&` from the styles as well, wherever it's used.
```suggestion
  .slick-slider {
```

2021-12-23 15:17 UTC, Anas-AlRamahi commented
This PR was fixed into a new PR called Rev-002: add reverifiplus and explorelistings from homepage. Last comments were resolved in the new PR as well.

2021-12-23 16:25 UTC, closed without merging