do small fixes
abukhadraop-or/reverifi pull request #310
Opened 2022-03-27 07:33 UTC by FarahJamal-business

### Jira URL

https://optimumpartners.atlassian.net/browse/JIRA_ISSUE_ID

### Description

_What problem is this branch meant to solve, what changes does it make, and how do these changes fix that problem?_

### Dependencies in Other PRs,Repo

_If this pull request relates to or depends on any changes in backend/frontend repo PR link it here._

### Testing Instructions

_How to test this and check for any possible regressions. Provide test data when applicable._

2022-03-27 15:54 UTC, mohdabed123 requested changes

2022-03-27 15:54 UTC, mohdabed123 commented on src/components/transaction-info/TransactionSummaryModal/transaction-summary-modal.styles.js
> +  min-width: 30rem;
will these effect mobile view ? if they do effect the mobile view can you please make it work to be more responsive

2022-03-27 15:54 UTC, mohdabed123 commented on src/components/transaction-info/TransactionSummaryModal/transaction-summary-modal.styles.js
> +  min-width: 30rem;
same thing here

2022-03-28 07:59 UTC, FarahJamal-business commented on src/components/transaction-info/TransactionSummaryModal/transaction-summary-modal.styles.js
> +  min-width: 30rem;
great point thank you!  
done

2022-03-28 11:59 UTC, mohdabed123 approved these changes

2022-03-28 11:59 UTC, merged