REV-551 fix garages with zero value
abukhadraop-or/reverifi pull request #328
Opened 2022-03-29 07:58 UTC by FarahJamal-business

### Jira URL

https://optimumpartners.atlassian.net/browse/REV-551
### Description

garages with zero value didn't appear

2022-03-29 08:48 UTC, mohdabed123 requested changes
0 is falsy so using double !! should do the job

2022-03-29 08:48 UTC, mohdabed123 commented on src/components/agent-details/CardInformation/index.jsx
> +          {garages >= 0 ? (
```suggestion
          {!!garages ? (
```

2022-03-29 08:48 UTC, mohdabed123 commented on src/components/home/FeaturedListingCard/index.jsx
> +              {garages >= 0 && (
```suggestion
              {!!garages &&  (
```

2022-03-29 08:48 UTC, mohdabed123 commented on src/components/home/FeaturedListingCard/index.jsx
> +              {garages >= 0 && (
```suggestion
              {!!garages  && (
```

2022-03-29 08:48 UTC, mohdabed123 commented on src/components/listing-search-page/Card/index.jsx
> +          {garages >= 0 && (
```suggestion
          {!!garages  && (
```

2022-03-29 08:48 UTC, mohdabed123 commented on src/components/listing-search-page/MapCard/index.jsx
> +        {garages >= 0 && (
```suggestion
        {!!garages && (
```

2022-03-29 14:47 UTC, FarahJamal-business commented on src/components/agent-details/CardInformation/index.jsx
> +          {garages >= 0 ? (
that's remove garage icon and eslint rules didn't accept it

2022-03-31 08:26 UTC, mohdabed123 approved these changes

2022-03-31 08:26 UTC, merged