create map component
abukhadraop-or/reverifi pull request #34
Opened 2021-12-30 18:03 UTC by mhn-opt98

A Map component contains markers that when hovering shows a specific component(listing , card , etc ...
![Screenshot from 2021-12-30 20-02-06](https://user-images.githubusercontent.com/87971384/147777149-15940120-a489-4c50-8ac2-b79348c2991a.png)
)

2022-01-03 19:52 UTC, AseelRousan-op commented on src/assets/icons/Group-red.svg
> +</svg>
```suggestion
</svg>

```

2022-01-03 19:52 UTC, AseelRousan-op commented on src/components/Map/Marker/index.jsx
> +  onMouseOverHandler: () => {},
isn't this function required prop here?

2022-01-03 19:52 UTC, AseelRousan-op commented on src/components/Map/index.jsx
> + * @param {Array} listings data needed for the Marker
```suggestion
 * @param {React.Component} ComponentOnMap Component that will appear on the map when hovering over the marker, this component must accept lng , lat, data as props
 * @param {boolean}         isMarkerShown  Wheather map markers or not
 * @param {Array}           listings       Data needed for the Marker
```

2022-01-03 19:52 UTC, AseelRousan-op commented on src/components/Map/Marker/index.jsx
> + * @param {Function} onMouseOverHandler hover event handler
```suggestion
 * @param {Object}  data                Data needed for the rendered component
 * @param {number}  lat                 Latitude to specify where the element has to be shown on the map
 * @param {number}  lag                 Longitude to specify where the element has to be shown on the map
 * @param {Function} onMouseOverHandler Hover event handler
```

2022-01-03 20:05 UTC, AseelRousan-op reviewed
Can we update the files structure here to move the `Marker` component out of the `Map` component, we can move them to a separate directory named map in the components directory like this:
components/map/Marker and Map here
or maybe we can move the `Map` to the shared folder since we'll be using this in most of the pages, correct?
cc: @abukhadraop ?

2022-01-03 20:16 UTC, Mahmoudzaid2994 commented on src/components/Map/Marker/index.jsx
> +
```suggestion

```

2022-01-03 20:17 UTC, Mahmoudzaid2994 commented on src/components/Map/index.jsx
> +
```suggestion

```

2022-01-03 20:18 UTC, Mahmoudzaid2994 commented on src/components/Map/index.jsx
> +  const showListingOnMap = (listingData) => {
Please add docs for this function

2022-01-03 20:18 UTC, Mahmoudzaid2994 commented on src/components/Map/index.jsx
> +  function getAverageCoordinate(coordsList, direction) {
Please add docs for this function

2022-01-03 20:18 UTC, Mahmoudzaid2994 commented on src/components/Map/index.jsx
> +  const getCenter = () => {
Please add docs for this function

2022-01-03 20:18 UTC, Mahmoudzaid2994 commented on src/components/Map/index.jsx
> +  useEffect(() => {
Please add docs for this function

2022-01-04 11:26 UTC, mhn-opt98 commented
> Can we update the files structure here to move the `Marker` component out of the `Map` component, we can move them to a separate directory named map in the components directory like this: components/map/Marker and Map here or maybe we can move the `Map` to the shared folder since we'll be using this in most of the pages, correct? cc: @abukhadraop ?

2022-01-04 11:27 UTC, AhmadAlShwaiki commented on src/components/Map/index.jsx
> +  function getAverageCoordinate(coordsList, direction) {
Please commit to using arrow functions.

2022-01-04 11:28 UTC, mhn-opt98 commented
> Can we update the files structure here to move the `Marker` component out of the `Map` component, we can move them to a separate directory named map in the components directory like this: components/map/Marker and Map here or maybe we can move the `Map` to the shared folder since we'll be using this in most of the pages, correct? cc: @abukhadraop ?

@abukhadraop

2022-01-04 11:29 UTC, AhmadAlShwaiki commented on src/components/Map/index.jsx
> +function Map({ ComponentOnMap, isMarkerShown, listings }) {
Please commit to camelCase for variables.
```
function Map({ componentOnMap, isMarkerShown, listings }) {
```

2022-01-04 11:39 UTC, AhmadAlShwaiki requested changes
Suggestion for naming and linting best practices

2022-01-04 11:42 UTC, AhmadAlShwaiki commented on src/pages/Home.jsx
> +const randomIntFromInterval = (min, max) => Math.random() * (max - min) + min;
Please use function documentation

2022-01-04 11:44 UTC, AhmadAlShwaiki commented on src/pages/Home.jsx
> +const maxLat = 39.84;
I can't see why do we need these hardcoded values.
If necessary you can add them in a separate file in one object 
for example:
```
const MAXIMUM_COORDINATES : {
```

2022-01-04 13:08 UTC, AhmadAlShwaiki commented on src/components/shared/Map/index.jsx
> +        bootstrapURLKeys={defaultProps.apiKey}
Can we use object destruct for the defaultProps? 
const { apiKey } = defaultProps;

2022-01-04 13:30 UTC, AhmadAlShwaiki commented on src/components/shared/Marker/index.jsx
> +import pinImg from '../../../assets/icons/Group-red.svg';
```suggestion
import pinImg from 'assets/icons/Group-red.svg';
```

2022-01-04 17:06 UTC, Mahmoudzaid2994 approved these changes

2022-01-04 17:09 UTC, AseelRousan-op commented
> > Can we update the files structure here to move the `Marker` component out of the `Map` component, we can move them to a separate directory named map in the components directory like this: components/map/Marker and Map here or maybe we can move the `Map` to the shared folder since we'll be using this in most of the pages, correct? cc: @abukhadraop ?
> 
> @abukhadraop

since we moved the Map component to the shared directory here, I'm gonna approve it in advance 👍

2022-01-04 17:09 UTC, AseelRousan-op approved these changes

2022-01-04 17:55 UTC, merged