REV-024: create my roles page
abukhadraop-or/reverifi pull request #35
Opened 2022-01-02 22:12 UTC by RaniaSAloun

Created my roles page with the following changes:

- added a new route for the page 
- created a page component in the pages folder
- created a table component (to be replaced with a shared component once built)
- created a cards container component, and a card component in the container component folder

Slide pages:
Desktop: https://optimumpartners.invisionapp.com/console/share/2Y34DAX6RD/819205008
Mobile: https://optimumpartners.invisionapp.com/console/share/3V3512T8G6/843334696

2022-01-03 09:54 UTC, AseelRousan-op requested changes

2022-01-03 09:54 UTC, AseelRousan-op commented on src/components/RoleCardsContainer/RoleCard/index.jsx
> +  // eslint-disable-next-line react/forbid-prop-types
can we git rid of this eslint disabling line here, 
```suggestion
 Icon: PropTypes.oneOf(['img', 'svg']).isRequired,
```

2022-01-03 09:54 UTC, AseelRousan-op commented on src/components/RolesTable/index.jsx
> +  Tr,
Can we Rename these components to have a meaningful name, for example:  TableCell, TableHead, TableRow

2022-01-03 09:54 UTC, AseelRousan-op commented on src/components/RoleCardsContainer/RoleCard/index.jsx
> +import PropTypes from 'prop-types';
Can we get the `RoleCard` component out of `RoleCardsContainer` directory and get these both components and the `RolesTable` component is `my-roles` directory so the structure will be something like this: 
my-roles=>RoleCardsContainer, RoleCard, RolesTable
and update the needed changes regarding this, please

2022-01-04 10:43 UTC, mohdabed123 approved these changes
small changes other than that LGTM

2022-01-04 10:43 UTC, mohdabed123 commented on src/components/my-roles/RolesTable/index.jsx
> +          {tableData.map((row) => (
```suggestion
          {tableData.map(({ id, property, role }) => (
```

2022-01-04 10:43 UTC, mohdabed123 commented on src/components/my-roles/RoleCardsContainer/role-cards-container.styles.js
> +export const Icon = (agent) => styled(agent)`
```suggestion
export const Icon = (icon) => styled(icon)`
```

2022-01-04 10:43 UTC, mohdabed123 commented on src/components/my-roles/RoleCardsContainer/role-cards-container.styles.js
> +  width: 100%;
do we need this?

2022-01-04 10:43 UTC, mohdabed123 commented on src/components/my-roles/RoleCardsContainer/role-cards-container.styles.js
> +  justify-content: flex-start;
is this needed?

2022-01-04 10:43 UTC, mohdabed123 commented on src/components/my-roles/RoleCardsContainer/index.jsx
> +      {roles.map((role) => (
```suggestion
      {roles.map(({ Icon, role, overview }) => (
```

2022-01-04 10:43 UTC, mohdabed123 commented on src/components/my-roles/RoleCard/role-card.styles.js
> +  flex-direction: column;
do we need these?

2022-01-04 13:46 UTC, RaniaSAloun commented on src/components/my-roles/RolesTable/roles-table.style.js
> +  border-radius: 0.375rem;
it adds a border to the table inside

2022-01-05 12:51 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCardsContainer/index.jsx
> +          role={role}
Please reduce the number of Props where possible
```suggestion
          key={role}
          data={ {role, overview, Icon} }
```

2022-01-05 13:12 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCard/role-card.styles.js
> +  width: 1.25rem;
```suggestion
  border-radius: 0.625rem;
```

2022-01-05 13:12 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCard/role-card.styles.js
> +  width: 1.25rem;
```suggestion
  width: 1.25rem;
  border-radius: 0.625rem;
```

2022-01-05 13:14 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCard/index.jsx
> +      <Rectangle clicked={isClicked}>{isClicked && <CheckIcon />}</Rectangle>
```suggestion
      <Rectangle isSelected={isClicked}>{isClicked && <CheckIcon />}</Rectangle>
```

2022-01-05 13:27 UTC, AhmadAlShwaiki commented on src/pages/MyRoles/my-roles.styles.js
> +  `}
```suggestion
  font-size: 1rem;
`;
```

2022-01-05 13:29 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCard/role-card.styles.js
> +`;
Can simply be an h3, no need for this component
```suggestion
export const RoleText = styled.h3`
`;
```

2022-01-05 13:31 UTC, AhmadAlShwaiki requested changes
some minor component and styling suggestions, otherwise looks really good.

2022-01-05 13:33 UTC, RaniaSAloun commented
@AhmadAlShwaiki For the comment on the checkbox style, it's a design change request, was discussed with @AseelRousan-op, the cards are represented as check-boxes not radio buttons.

2022-01-05 14:00 UTC, RaniaSAloun commented
@AhmadAlShwaiki 
for this comment: 'Can simply be an h3, no need for this component' on the RoleText styled component;
I've read on w3schools that we shouldn't use headings to make text big or bold, headings should be used for main headings to be used by search engines.
https://www.w3schools.com/html/html_headings.asp

Do you still want it replaced?

2022-01-05 15:23 UTC, AhmadAlShwaiki commented
> @AhmadAlShwaiki for this comment: 'Can simply be an h3, no need for this component' on the RoleText styled component; I've read on w3schools that we shouldn't use headings to make text big or bold, headings should be used for main headings to be used by search engines. https://www.w3schools.com/html/html_headings.asp
> 
> Do you still want it replaced?

What matters here is that we shouldn't make/reinvent a styled component for each html element when we simply could use one. If you seek to match the advise mentioned on the website you can keep it.

2022-01-05 15:24 UTC, AhmadAlShwaiki approved these changes

2022-01-06 09:38 UTC, mohdabed123 approved these changes

2022-01-09 20:46 UTC, AseelRousan-op approved these changes

2022-01-09 20:46 UTC, AseelRousan-op commented on src/components/my-roles/RoleCardsContainer/index.jsx
> + * @param {func} props.setSelectedRoles Sets selected roles.
```suggestion
 * @param {Object} props                  Props passed to RoleCardsContainer.
 * @param {func}   props.setSelectedRoles Sets selected roles.
```

2022-01-11 16:37 UTC, AseelRousan-op approved these changes
👍

2022-01-11 17:13 UTC, Mahmoudzaid2994 approved these changes

2022-01-11 17:14 UTC, merged