REV-019: Create agent details page
abukhadraop-or/reverifi pull request #37
Opened 2022-01-03 15:08 UTC by moenaser4

### Description

Create agent details Page

Figma link:
https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A7906

2022-01-05 13:18 UTC, mohdabed123 requested changes
Note: agent contact form is also created in this [PR](https://github.com/abukhadraop-or/reverifi/pull/23) , probably we would want to clean up the code and create one component to replace both

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentInformation/agent-information.style.js
> +  }
can we use h2 instead

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentInformation/index.jsx
> +            <StyledImg src={AgentPhoto} width="300" />
```suggestion
            <StyledImg src={AgentPhoto} />
```

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentInformation/index.jsx
> +              {agentData.map((info) => (
```suggestion
              {agentData.map(({ key, value }) => (
```

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentInformation/index.jsx
> +              {companyData.map((info) => (
```suggestion
              {companyData.map(({ key, vlalue}) => (
```

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +`;
can we use h1 instead

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +`;
```suggestion
```

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentInformation/agent-information.style.js
> +  background-color: ${colors.white};
this feels off, not consistent with the rest of the agent section

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +  display: flex;
```suggestion
```

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +  }
can we use h2 or h3 here instead
```suggestion
```

2022-01-05 13:18 UTC, mohdabed123 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +  }
can we put it in its own styled component
```suggestion
```

2022-01-05 14:46 UTC, moenaser4 commented on src/components/AgentDetails/AgentInformation/agent-information.style.js
> +  flex-direction: column;
Yes, this container includes the profile image and social media icons container.

2022-01-05 14:49 UTC, moenaser4 commented on src/components/AgentDetails/AgentInformation/agent-information.style.js
> +  width: 100%;
Yes, this is to handle viewports larger than 1440px

2022-01-05 14:50 UTC, moenaser4 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +`;
this is to handle viewports larger than 1440px

2022-01-05 14:52 UTC, AhmadAlShwaiki commented on src/components/AgentDetails/AgentInformation/index.jsx
> +function AgentDetails() {
Please use different functions names, this is essential.

2022-01-05 14:58 UTC, AhmadAlShwaiki commented on src/components/AgentDetails/ContactAgent/contact-agent.style.js
> +  resize: none;
Please remove any unneeded css here and throughout the page
```suggestion
```

2022-01-05 15:08 UTC, AhmadAlShwaiki commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +    height: 1.75rem !important;
Please remove if not needed
```suggestion
    height: 1.75rem;
```

2022-01-05 15:14 UTC, moenaser4 commented on src/components/AgentDetails/AgentListings/agent-listings.style.js
> +  display: flex;
flex here used in case there is more than one tag such as (RENT, SALE).

2022-01-05 15:14 UTC, moenaser4 commented on src/components/AgentDetails/AgentInformation/agent-information.style.js
> +  background-color: ${colors.white};
followed the design 
https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A7906

2022-01-05 15:16 UTC, AhmadAlShwaiki requested changes
Noticed a lot of unneeded styled components, css values, please try to decrease and clean up as much as possible. 🙏 
Couldn't see this part (navigated to `/agent-details`) , not sure if I'm missing something.

![image](https://user-images.githubusercontent.com/81982465/148241455-338faa6c-a43f-442d-b66c-2b7fd33e1b7f.png)

2022-01-09 21:44 UTC, AseelRousan-op requested changes

2022-01-09 21:44 UTC, AseelRousan-op commented on src/components/agent-details/AgentListings/agent-listings.style.js
> +  top: ${(props) => (props.top ? '1rem' : null)};
This can be enhanced
```suggestion
  ${({ isBottom }) => (isBottom ? `bottom: 1rem;` : `top: 1rem;`)}
  ${({ isRight }) => (isRight ? `right: 1rem;` : `left: 1rem;`)}
```

2022-01-09 21:44 UTC, AseelRousan-op commented on src/components/agent-details/AgentListings/index.jsx
> +              <CornerItems left top>
```suggestion
              <CornerItems isRight={false} isBottom={false}>
```

2022-01-09 21:44 UTC, AseelRousan-op commented on src/components/agent-details/AgentListings/index.jsx
> +              <CornerItems right top>
```suggestion
              <CornerItems isRight isBottom={false} >
```

2022-01-09 21:44 UTC, AseelRousan-op commented on src/components/agent-details/AgentListings/index.jsx
> +              <CornerItems bottom left>
```suggestion
              <CornerItems isBottom isRight={false} >
```

2022-01-09 21:44 UTC, AseelRousan-op commented on src/components/agent-details/AgentListings/index.jsx
> +            <CardInformation>
Can we move the CardInformation here to a separate component to simplify the AgentListings component, and I think it will be a dynamic component later, not all the services will be added for each card, also we can rename it to something like AvailableServices, for example?

2022-01-10 16:39 UTC, AhmadAlShwaiki commented on src/components/agent-details/ContactAgent/index.jsx
> +      <h2>Contact John Doe</h2>
Same here

2022-01-10 16:39 UTC, AhmadAlShwaiki commented on src/components/agent-details/ContactAgent/index.jsx
> +function ContactAgent() {
```suggestion
function ContactAgentForm() {
```

2022-01-10 16:53 UTC, AhmadAlShwaiki commented on src/components/agent-details/ContactAgent/index.jsx
> +function ContactAgent() {
Todo: this is a mock component that will be deduped with a shared form in the future

2022-01-10 16:54 UTC, AhmadAlShwaiki approved these changes
LGTM

2022-01-12 09:40 UTC, Mahmoudzaid2994 approved these changes

2022-01-12 09:40 UTC, merged