REV-029-refactor-verify-phone-page-file-structure
abukhadraop-or/reverifi pull request #39
Opened 2022-01-06 13:05 UTC by IbrahimAldereni-socuimtech

2022-01-09 21:06 UTC, AseelRousan-op requested changes

2022-01-09 21:06 UTC, AseelRousan-op commented on src/components/shared/Sidebar/sidebar.styles.js
> +    }}
can we revert this change here 
```suggestion
animation: ${({ isCollapsed }) => (isCollapsed ? fadeOut : fadeIn)}
```

2022-01-09 21:06 UTC, AseelRousan-op commented on src/components/shared/Sidebar/index.jsx
> +  const [isCollapsed, setIsCollapsed] = useState(' ');
why we're removing the initial false here ?

2022-01-10 08:48 UTC, AseelRousan-op commented
@momokdad I talked to Ibrahim and he said that you'll address these changes, Thanks in advance

2022-01-10 09:00 UTC, AseelRousan-op commented
Talked to @momokdad I'll mark the above changes as resolved

2022-01-11 21:16 UTC, AseelRousan-op approved these changes

2022-01-12 08:11 UTC, AhmadAlShwaiki approved these changes
Looks good!

2022-01-12 08:26 UTC, mohdabed123 approved these changes
LGTM

2022-01-12 09:19 UTC, merged