REV-32- finish dashboard page with shared tab, table, tooltip, accordion
abukhadraop-or/reverifi pull request #44
Opened 2022-01-16 05:04 UTC by IbrahimAldereni-socuimtech

- figma link:
https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A21013

2022-01-23 14:33 UTC, AhmadAlShwaiki commented on docker-compose.yml
> +      - 3000:80
Can we revert this?

2022-01-23 14:52 UTC, AhmadAlShwaiki commented on src/components/dashboard/DashboardWrapper/index.jsx
> +            <option value="">Status</option>
I think this should be a placeholder not an option. This fix can be done in the root component `DropdownMenu ` We can fix this in another PR or here.

```suggestion
```

2022-01-23 14:52 UTC, AhmadAlShwaiki commented on src/components/dashboard/DashboardWrapper/index.jsx
> +          <DropdownMenu name="status" leftIcon={dropdownIcon1}>
```suggestion
          <DropdownMenu name="Status" leftIcon={dropdownIcon1}>
```

2022-01-23 14:53 UTC, AhmadAlShwaiki commented on src/components/dashboard/DashboardWrapper/index.jsx
> +          <DropdownMenu name="role" leftIcon={dropdownIcon2}>
```suggestion
          <DropdownMenu name="Role" leftIcon={dropdownIcon2}>
```

2022-01-23 14:54 UTC, AhmadAlShwaiki commented on src/components/dashboard/DashboardWrapper/index.jsx
> +            <option value="2">buyer</option>
```suggestion
            <option value="1">Seller</option>
            <option value="2">Buyer</option>
```

2022-01-23 14:56 UTC, AhmadAlShwaiki commented on src/components/dashboard/DashboardWrapper/index.jsx
> +          <DropdownMenu name="role" leftIcon={dropdownIcon2}>
Names are not clear here, please fix the above too if possible. 🙏 
```suggestion
          <DropdownMenu name="role" leftIcon={roleDropDownIcon}>
```

2022-01-23 15:35 UTC, AhmadAlShwaiki commented on src/components/dashboard/OffersTable/index.jsx
> +                <OfferDetails>
I suppose we can replace these divs with `<ul>` or table <tr> ?
```suggestion
```

2022-01-23 15:38 UTC, AhmadAlShwaiki commented on src/components/dashboard/OffersTable/offers-table.styles.js
> +  border-bottom: 0.0625rem solid ${colors.midGray};
```suggestion
  border-bottom: 0.06rem solid ${colors.midGray};
```

2022-01-23 15:39 UTC, AhmadAlShwaiki commented on src/components/shared/Table/table-styles.js
> +    padding: 1.6875rem;
```suggestion
    padding: 1.7rem;
```

2022-01-23 15:47 UTC, AhmadAlShwaiki commented on src/components/shared/Tooltip/tooltip.styles.js
> +  color: #fff;
```suggestion
  color: ${colors.white};
```

2022-01-23 15:48 UTC, AhmadAlShwaiki commented on src/components/shared/Tooltip/tooltip.styles.js
> +    border-width: 0.4375rem;
```suggestion
    border-width: 0.5rem;
```

2022-01-23 15:51 UTC, AhmadAlShwaiki requested changes
Changes mainly focus on dropdown menu selection
css value auditing and standards
proper use of html elements

2022-01-24 14:12 UTC, IbrahimAldereni-socuimtech commented on src/components/dashboard/DashboardWrapper/index.jsx
> +            <option value="">Status</option>
This is a select tag it doesn't have placeholder

2022-01-25 09:24 UTC, AhmadAlShwaiki commented on src/components/dashboard/DashboardWrapper/index.jsx
> +            <option value="">Status</option>
Please change them to a label, as these are not supposed to be an option

2022-01-26 09:22 UTC, AhmadAlShwaiki commented on src/components/shared/DropdownMenu/index.jsx
> +        smallBorderRadius={smallBorderRadius}
Cant see why this is named this way 🤔 
```suggestion
        borderRadius={borderRadius}
```

2022-01-26 17:25 UTC, IbrahimAldereni-socuimtech commented on src/components/shared/DropdownMenu/index.jsx
> +        smallBorderRadius={smallBorderRadius}
this is not a number, this is true/false value if the border raduis small or not

2022-01-26 17:42 UTC, AhmadAlShwaiki commented on src/components/shared/DropdownMenu/index.jsx
> +        smallBorderRadius={smallBorderRadius}
Can't see why we would need this, please remove the prop and use the current style.

2022-01-26 17:43 UTC, AhmadAlShwaiki requested changes
Adjust DropdownMenu by removing border-radius styling prop

2022-01-26 17:54 UTC, IbrahimAldereni-socuimtech commented on src/components/shared/DropdownMenu/index.jsx
> +        smallBorderRadius={smallBorderRadius}
this is a shared component sometimes the menu have small raduis and sometimes not

2022-01-26 19:45 UTC, AhmadAlShwaiki commented on src/components/shared/DropdownMenu/index.jsx
> +        smallBorderRadius={smallBorderRadius}
can be adjusted via styled components. Just like the implementation of shared `<Button/>`

2022-01-27 18:16 UTC, IbrahimAldereni-socuimtech commented on src/components/shared/DropdownMenu/index.jsx
> +        smallBorderRadius={smallBorderRadius}
yes i already done that its adjust it by styled component ??

2022-01-30 13:05 UTC, merged