add schedule component
abukhadraop-or/reverifi pull request #45
Opened 2022-01-16 07:50 UTC by IbrahimAljabrST

- figma link: https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A24048

2022-01-25 22:02 UTC, Mahmoudzaid2994 commented on docker-compose.yml
> +      - 3000:80
Please revert this

2022-01-25 22:04 UTC, Mahmoudzaid2994 commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +          for (let i = 0; i < daysNumber + 1; i++) {
can you try to find another way than for loop

2022-01-25 22:04 UTC, Mahmoudzaid2994 commented on src/components/edit-listing-schedule/TimeInput/index.jsx
> +function TimeInput({
add docs

2022-01-25 22:05 UTC, Mahmoudzaid2994 commented on src/components/shared/Switch/index.jsx
> +  days: PropTypes.array.isRequired,
use objectOf and arraOf

2022-01-26 10:40 UTC, IbrahimAljabrST commented on src/components/shared/Switch/index.jsx
> +  days: PropTypes.array.isRequired,
waiting for the backend and database for the real data type

2022-01-26 17:47 UTC, AhmadAlShwaiki commented on package.json
> +    "react-datepicker": "^4.6.0",
```suggestion
    "react-datepicker": "^4.5.0",
```
Please revert back to older version, unless its necessary.

2022-01-26 17:50 UTC, AhmadAlShwaiki commented on src/routes.js
> +    path: '/edit-listing-schedule',
```suggestion
    path: '/listing-schedule/edit',
```

2022-01-26 18:57 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/DateInput/index.jsx
> +      placeholderText="10-05-2021  - 16-05-2021"
```suggestion
      placeholderText="Click to select a date"
```
I feel this can get confusing for users.

2022-01-26 19:02 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/edit-listing-schedule.js
> +  border: 0.06rem ${colors.mineShaft}16 solid;
```suggestion
  border: 0.06rem ${colors.midGray} solid;
```
🤷

2022-01-26 19:03 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/edit-listing-schedule.js
> +  /* while you picking a date color */
```suggestion
  /* while picking a date color */
```

2022-01-26 19:05 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/edit-listing-schedule.js
> +    background-color: ${colors.green}99;
```suggestion
    background-color: ${colors.green};
    opacity: 0.5;
```
Please don't attach string parts to the variables. The point is to keep the css values comprehensive and clear.

2022-01-26 19:09 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +  const [dateRangeValue, setDateRangeValue] = useState(null);
```suggestion
  const [dateRange , setDateRange] = useState(null);
```

2022-01-26 19:09 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +          <DatePickerInput setDateRangeValue={setDateRangeValue} />
```suggestion
          <DatePickerInput onChange={setDateRange} />
```

2022-01-26 19:29 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +      if (daysDiff <= 432000000) {
What is this value? Half a week?
```suggestion
```

2022-01-26 19:38 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +    console.log(`🚀🚀 ~~ onSubmit ~~ days`, days);
This always submits all the mock data days, regardless of what I choose. 
![image](https://user-images.githubusercontent.com/81982465/151234442-d8f65854-6cf4-4db4-b4d6-9c52b6fda45d.png)

2022-01-26 19:40 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +      setDays([...days], (day.available = true));
Isn't this just alias to the prop above? 
```suggestion
```

2022-01-26 19:43 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +    days.map((day) => {
Please use id rendering instead, I know we're dealing with only 7 items but still, we loop a lot.
Can you please change the implementation so that each day has a unique id
Then we can loop through id of strings, set ones that are selected with the proper value say: `selected = false`

2022-01-26 19:47 UTC, AhmadAlShwaiki requested changes
Further adjustments mainly on the implementation of page response to the date picker

2022-01-27 15:29 UTC, IbrahimAljabrST commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +      setDays([...days], (day.available = true));
outOfDate will work only if it was less than week

2022-01-27 15:30 UTC, IbrahimAljabrST commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +      if (daysDiff <= 432000000) {
5 days

2022-02-24 14:08 UTC, mohdabed123 requested changes

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing-schedule/Switch/index.jsx
> +  return (
```suggestion
  const {active,label} = day
  
  return (
```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing-schedule/TimeInput/index.jsx
> +  const handelChange = (e) => {
```suggestion
   const {active,start,end} = day;
  
    const handelChange = (e) => {
```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing/Schedule/EditListingSchedule.jsx
> +}
```suggestion
}

```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing-schedule/TimeInput/index.jsx
> +};
```suggestion
};

```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing/Tabs/index.jsx
> +        activePage={+tab || 0}
```suggestion
        activePage={tab}
```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/shared/Tabs/index.jsx
> +};
add the rest of the props

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing/Tabs/index.jsx
> +  const tab = searchParams.get('tab') || '';
```suggestion
  const tab = searchParams.get('tab') || 0;
```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +// eslint-disable-next-line react/prop-types
```suggestion
// eslint-disable-next-line react/prop-types
```
```suggestion
```

2022-02-24 14:08 UTC, mohdabed123 commented on src/components/edit-listing-schedule/ListingSchedule/index.jsx
> +                    <p>To</p>
```suggestion
                    <span>To</span>
```

2022-02-24 15:26 UTC, IbrahimAljabrST commented on src/components/edit-listing/Tabs/index.jsx
> +        activePage={+tab || 0}
this need a number, the tab is string so it will work only if we change it to number,
the default value is 0 for the first tab

2022-02-24 15:29 UTC, IbrahimAljabrST commented on src/components/shared/Tabs/index.jsx
> +};
the other props are required we cant add them to default props .

2022-02-24 15:45 UTC, mohdabed123 approved these changes

2022-02-24 15:50 UTC, AhmadAlShwaiki commented on src/components/edit-listing-schedule/DateInput/date-input.style.js
> +  outline: none;
```suggestion
```

2022-02-24 15:55 UTC, AhmadAlShwaiki commented on src/utils/helpers.js
> + * @return {Number} difference between 2 dates
This comment block is outdated please adjust

2022-02-24 15:56 UTC, AhmadAlShwaiki commented on src/utils/helpers.js
> +export const getDifferenceBetweenTwoDates = (firstDate, secondDate, period) => {
Date can be a string instead of converting it here

2022-02-24 15:57 UTC, AhmadAlShwaiki commented on src/utils/helpers.js
> +  const diffInDays = Math.ceil(diffInMs / (1000 * 60 * 60 * 24) + 1);
There can be no assurance that the first is less than the second. If we want an absolute value we should replace with 
```suggestion
  const diffInDays = Math.abs(Math.ceil(diffInMs / (1000 * 60 * 60 * 24) + 1));
```

2022-02-24 15:57 UTC, AhmadAlShwaiki approved these changes

2022-02-24 16:14 UTC, IbrahimAljabrST commented on src/utils/helpers.js
> +export const getDifferenceBetweenTwoDates = (firstDate, secondDate, period) => {
converting it here so it will accept all the kind of date

2022-02-24 16:20 UTC, merged