REV-38-link user roles with backend
abukhadraop-or/reverifi pull request #52
Opened 2022-01-25 16:28 UTC by IbrahimAldereni-socuimtech

### Description
- link user roles with backend
- backend PR: 
https://github.com/abukhadraop-or/reverifi-api/pull/14

![333](https://user-images.githubusercontent.com/92721815/151017804-ef1eda93-ef19-4acd-aa41-f4f2bf62d81d.png)

2022-01-25 22:26 UTC, Mahmoudzaid2994 commented on src/services/user.js
> + * @param {Array(String)} rolesIds roles ids array
add new line please

2022-01-26 20:35 UTC, AhmadAlShwaiki commented on .vscode/settings.json
> +  "prettier.trailingComma": "all",
Please revert the above and rebase once this [PR](https://github.com/abukhadraop-or/reverifi/pull/54) is merged

2022-01-26 20:36 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCard/index.jsx
> +  const { Icon, overview, role, id, dbRoles } = data;
```suggestion
  const { Icon, overview, role, id, dbRoles:selectedRoles } = data;
```
```suggestion
  const { Icon, overview, role, id, dbRoles } = data;
```

2022-01-26 20:38 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCardsContainer/data.js
>    },
```suggestion
    selected: true
  },
```

2022-01-26 20:40 UTC, AhmadAlShwaiki commented on src/components/my-roles/Roles/index.jsx
> +  const startProcessHandler = async () => {
```suggestion
  const handleOnClick = async () => {
```

2022-01-26 20:41 UTC, AhmadAlShwaiki requested changes
Looks really good, just few tweaks

2022-01-27 12:50 UTC, AhmadAlShwaiki commented on src/components/my-roles/RoleCardsContainer/index.jsx
> +  const [dbRoles, setDbRoles] = useState([]);
Please adjust here as well, the name isn't appropriate.  

https://github.com/abukhadraop-or/reverifi/pull/52/files#diff-d141e3e38da901f992e4c9af91db349c4137ec5f2571227854f6932f4d8a757fR15

2022-01-27 21:21 UTC, AhmadAlShwaiki approved these changes
Looks good!

2022-01-30 13:49 UTC, merged