Create homepage's navbar and storyboard
abukhadraop-or/reverifi pull request #6
Opened 2021-12-12 11:34 UTC by hosamAjlouni-op

### Description
- renamed Header to NavBar.
- implementing NavBar component and styled components.
- implementing storyboard component and styled components.
- added input and input group as shared components - could be improved - based on upcoming requirements.

2021-12-12 16:58 UTC, abukhadraop requested changes
General notes
- we should keep an empty line between CSS blocks 
   ```js
    const Item = styled.div`
      ...
      // empty line
      p {
       ...
      }
     // empty line
      ${mq.tablet`
       ....
      `}
    `;
   ```
- try to avoid percentage values as much as possible

2021-12-12 16:58 UTC, abukhadraop commented on src/styles/global-styles.js
> +    font-family: "Montserrat", Helvetica, sans-serif;
why this change is made ?

2021-12-12 16:58 UTC, abukhadraop commented on src/styles/global-styles.js
> +    font-family: 'Montserrat', sans-serif;
also here, why this font changed ?

2021-12-12 16:58 UTC, abukhadraop commented on src/styles/global-styles.js
> +    color: ${colors.mineShaft};
please keep the black as the default color, you can override it in your components if its needed

2021-12-12 16:58 UTC, abukhadraop commented on src/styles/global-styles.js
> +    padding-top: 5rem;
adding this padding here is a bad idea, we may have some pages that do not have the navbar or have it but it's not sticky, this spacing should be made in the navbar so we can change it in the future if we need it without affecting the whole app

2021-12-12 16:58 UTC, abukhadraop commented on src/styles/global-styles.js
>      overflow: hidden;
i think this line should be removed

2021-12-12 16:58 UTC, abukhadraop commented on src/styles/breakpoints.js
> +/* eslint-disable sort-keys */
👍

2021-12-12 16:58 UTC, abukhadraop commented on src/components/Shared/Input/input.styles.js
> +export const StyledInput = styled.input`
i think this component should be merged with `StyledInputGroup` in one shared component that can be configured throw props
please check these comments 
https://github.com/abukhadraop-or/reverifi/pull/1#discussion_r767247575
https://github.com/abukhadraop-or/reverifi/pull/1#discussion_r767248388

2021-12-12 16:58 UTC, abukhadraop commented on src/components/Storyboard/storyboard.styles.js
> +    margin-top: 1.8125rem;
this component should not have a top padding, the top spacing should be handled by the navbar, also i dont see any effect of removing the other styles
```suggestion
```

2021-12-12 16:58 UTC, abukhadraop commented on src/components/Storyboard/storyboard.styles.js
> +  width: 100%;
i think you can set use `flex:1` here to split the container in half without using percentage

2021-12-12 16:58 UTC, abukhadraop commented on src/components/Storyboard/storyboard.styles.js
> +  height: 100%;
same as above 👆

2021-12-12 16:58 UTC, abukhadraop commented on src/components/Storyboard/storyboard.styles.js
> +    width: 78.613%;
leats avoid these magic numbers, you can apply some padding to the container to get the same result

2021-12-12 16:58 UTC, abukhadraop commented on src/components/Storyboard/storyboard.styles.js
> +    width: 75%;
same here, lets try to avoid using the percentage values

2021-12-13 09:20 UTC, hosamAjlouni-op commented on src/styles/global-styles.js
> +    font-family: "Montserrat", Helvetica, sans-serif;
my bad

2021-12-19 16:53 UTC, Mahmoudzaid2994 commented on src/components/Navbar/UserControlSection.jsx
> +// import PropTypes from 'prop-types';
please remove this line

2021-12-19 16:53 UTC, Mahmoudzaid2994 commented on src/components/Shared/DropDown/dropDown.styles.js
> +  min-width: 200px;
please convert all px to rem

2021-12-19 16:53 UTC, Mahmoudzaid2994 commented on src/components/Shared/DropDown/index.jsx
> +/* eslint-disable no-console */
remove this line

2021-12-19 16:53 UTC, Mahmoudzaid2994 commented on src/components/Shared/Input/index.jsx
> +function Input({ left, right, placeholder, type, color }) {
using meaningful names instead of right and left

2021-12-19 16:53 UTC, Mahmoudzaid2994 commented on src/components/Shared/Input/input.styles.js
> +  box-shadow: 0rem 0.0625rem 0.1875rem #22222229;
add this color `#22222229;` to colors file then use it

2021-12-23 12:38 UTC, MZeq commented on src/assets/images/joinNow.svg
> +<svg width="117" height="40" viewBox="0 0 117 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Can we change the name of this file to be kebab-case.

2021-12-23 12:42 UTC, MZeq reviewed
Good job, a few comments and I think that it's good to go.

The branch name must not contains any special characters, please create a new PR with the branch name `REV-001-.create-homepage-navbar-and-storyboard` we can't use `'` or any other special characters in it.

2021-12-23 12:42 UTC, MZeq commented on src/assets/images/joinNow.svg
> +<svg width="117" height="40" viewBox="0 0 117 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Can we change the name of this file to be kebab-case.

2021-12-23 12:42 UTC, MZeq commented on src/assets/images/locationPin.svg
> +<svg viewBox="0 0 12 16" fill="none" xmlns="http://www.w3.org/2000/svg">
For this file as well. and all the other files.

2021-12-23 12:42 UTC, MZeq commented on src/components/Navbar/navbar.styles.js
> +import styled from 'styled-components';
Do you have the rule to organize the imports, if not please add it and reorganize your imports in all of your files.

2021-12-23 16:51 UTC, closed without merging